### ISSUE TITLE
Email notification with change summary

### ISSUE THREAD

**Issue by fourg** [digitalocean/netbox#1017]
A feature request that allows us to set an email or multiple email addresses which are notified any time a change to our netbox is made which shows the same details as the Recent Activity pane does today.  Would be helpful to know about activity without the need to visit the site each time.  We'd be sending those emails for example to a Slack channel we use so everyone is aware and it may prompt them for discussion in real time.

Thanks!

**Comment by jeremystretch** [comment]
Webhooks (#81) are probably a more efficient and more flexible approach. In either case, we'd need to figure out the framework for transmitting messages triggered by a request, ideally asynchronously.

An RSS feed of recent activity has also been suggested. That's probably not applicable to your use case though.

**Comment by InsaneSplash** [comment]
I wrote a small Perl script which sends out a daily email with the last days new Tenants, Sites and devices. I found that it was well received by our teams as it keeps them up to date with the relevant activity.

The script interagates the event log table in postgres directly due to it not available as yet truth the API.

**Comment by jeremystretch** [comment]
Closing this out in favor of #81
