### ISSUE TITLE
Add etherchannel interface type

### ISSUE THREAD

**Issue by markve-sa** [digitalocean/netbox#105]
Please may we be able to create an etherchannel interface type with the ability to add physical interfaces to them

Amazing work so far. Most comprehensive IPAM I've seen

**Comment by ryanmerolle** [comment]
We should think about this carefully to include things like MLAG.

**Comment by rdujardin** [comment]
An idea : simply add a boolean field "lag" to Interface.
Interfaces connected to a lag interface can either be lag too which means a true connection between two lags, or not be lag which means they belong to the lag.
It's simple, it allows to point at interfaces no matter lagged or not (compatible with #267 for instance), it allows MLAG, etc.

**Comment by specialcircumstances** [comment]
I'd say that this needs to be a seperate Interface Type, in that it needs to have a relationship to it's component interfaces. I like the LAG "name" as it's generic, and is used with many platforms. I'd suggest fields would need to include LAG type (e.g. LACP, PAGP, "Vanilla Etherchannel", VPC, VPC+, etc...).
For best use, it should be possible to exist over multiple devices, which is common now.
To that end, perhaps it needs to be a new model, with a new ForeignKey (rather than a boolean) looking up to it in the Interface model. I think this would work in all cases, although there would be the (very useful) need to sanity check the membership.
The difficulty might be in representing this in the device Interface list, as it's a different table. That said, looking at the Device view, a LAG box could sit above the Interfaces box?

**Comment by specialcircumstances** [comment]
Yay :)
