### ISSUE TITLE
Custom Field Data Searching

### ISSUE THREAD

**Issue by jennec** [digitalocean/netbox#1077]
Searching for Custom content data seems to fail.  

For example:  
Create a custom field for IP Addresses
Add data to that custom field on an IP address object.
Go to the Front Page and search for this data or part of this data in "Search IPs" field.  
The resulting IP object will not be found.

Similarly in IP Addresses page, you can search for the Custom Field data by using the Custom Field Search box on the right side of the page.  But you cannot enter partial data in this field and get a result.  It has to be all data contained in that field.  

Can the search functions be modified to include searchung custom fields from the front page and also partial data? (for example searching for "url1" when the data in the field may contain "URL1, URL2, URL3, ULR4" etc.

**Comment by t0i** [comment]
> Similarly in IP Addresses page, you can search for the Custom Field data by using the Custom Field Search box on the right side of the page. But you cannot enter partial data in this field and get a result. It has to be all data contained in that field.

This should be resolved in - https://github.com/digitalocean/netbox/commit/583830c652c2b46c44df21ff0779dad6101932cc

However this request also wants global search to return Custom Fields in global search results (rather than the Custom Field Search under IP Address).

I think enough people want Global search to search through Custom Fields that we should open a new discussion on how to make this happen. It was discussed briefly in https://github.com/digitalocean/netbox/issues/1190#issuecomment-306029330

As such this issue can probably be closed now and further discussion to the topic of Searching Custom Fields can take place in issue 1190.

**Comment by jeremystretch** [comment]
@t0i agreed. Closing this one out because #1190 has more discussion attached to it.
