### ISSUE TITLE
v2-beta various bugs

### ISSUE THREAD

**Issue by NetTinkerer** [digitalocean/netbox#1105]
### Issue type: bug report

**Python version: 2.7
**NetBox version: v2-beta

During installation I had to fix the following things 

- pytz is missing from requirement file
- pyasn1 is missing from requirement file
- had to add libjpeg-dev and python-pyparsing packages
- python-ldap package is not installed by default (could be my installation) 
- ldap is not working for me with the same config i used as for 1.8.4.

**Comment by jeremystretch** [comment]
> pytz is missing from requirement file
> pyasn1 is missing from requirement file

These are not direct requirements of the project and don't need to be listed.

> had to add libjpeg-dev and python-pyparsing packages

This should not be necessary. If you believe this is a bug, please open a bug report specifically for this including the steps needed to reproduce as indicated in out contributing guidelines.

> python-ldap package is not installed by default (could be my installation)

The LDAP package is not installed by default because not everyone uses LDAP for authentication.

> ldap is not working for me with the same config i used as for 1.8.4.

Please post to the mailing list if you require configuration assistance.
