### ISSUE TITLE
Allow Custom Fields on Inventory Items.

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1120]
### Issue type: Feature Request

I'd like to ask if it can be allowed to define Custom Fields on Inventory Items. It would help us with tracking certain information, that is probably unique to our organisation, like the purpose of a disk (e.g. whether a disk is built-in but spare).

Custom Fields have proven to be ideally for such use-cases, which are specific to one's organisation. It would therefore be great to have them available on Inventory Items.

**Comment by jeremystretch** [comment]
I don't think it makes sense to enable custom fields on inventory items. The model's role is still a bit ambiguous but it's intended to represent hardware components gleaned through some form of automated inventory. Additionally, due to the hierarchical arrangements of inventory items, including custom fields would introduce a substantial performance penalty.

You've also opened #1121 for the addition of some built-in fields for the InventoryItem model, which I think is preferable to enabling custom fields. I'm going to close out this ticket in favor of #1121; we can revisit the idea in the future if the agreed-upon built-in fields don't suffice.
