### ISSUE TITLE
Global Topology Maps Connections types

### ISSUE THREAD

**Issue by nicke94** [digitalocean/netbox#1177]
### Issue type: feature request

In the Topology Maps all the connections look the same, it would be nice to be able to differentiate the different types of connections between devices.

Examples of improvements:
- Show/hide Planned connections.
- Color code LAG interfaces.
- Color code Port types.

**Comment by jeremystretch** [comment]
I want to avoid getting too carried away with the topology maps, at least until we have a more robust manner of rendering them.

> Show/hide Planned connections.

We can render planned connections as dashed/dotted lines.

> Color code LAG interfaces.

Each member in a LAG is rendered separately. We could color-code LAG members, but this wouldn't differentiate one set of members from another.

> Color code Port types.

There aren't enough readily discernible colors for this to be practical.

**Comment by nicke94** [comment]
I understand,

Maybe you could render LAGs as dotted lines and/or use different background or outline colors. 

With Port types I meant more like link speeds, my bad. Like different colors for different speeds.

**Comment by jeremystretch** [comment]
There isn't really any reasonable way (AFAICT) of representing LAGs using graphviz. It is possible to draw a single line with multiple [peripheries](http://www.graphviz.org/doc/info/attrs.html#d:peripheries) but it looks really bad because it doesn't attach nicely to the nodes.

I don't like assigning colors to edges because a) you quickly run out of colors and b) the lighter-colored edges end up being harder to see. Keep in mind that topology maps are not intended to replace proper drawings; they're a convenience function just to quickly generate a basic map.

We can revisit these ideas in the future if we adopt something more robust than graphviz, but for I'd like to avoid doing too much with it.
