### ISSUE TITLE
Make site facility field unique

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1192]
When adding a facility ID to a Site, can it be checked for uniqueness?

**Comment by jeremystretch** [comment]
Leaving this one open for discussion.

**Comment by jeremystretch** [comment]
I'm going to decline this feature request because IMO it's a perfectly valid use case to have two or more sites in the same facility. (Keep in mind that unlike the Rack model's `facility_id` field, this field is not used for the identification of an object.) For example, a company might have multiple physical presences in a datacenter and treat each as an independent site within e.g. Equinix DC6. Plus, changing a long established non-unique field to a unique field is bound to cause issues for some users.

**Comment by InsaneSplash** [comment]
OK, thanks for the reply.
