### ISSUE TITLE
Add naming options for devices in rack units display

### ISSUE THREAD

**Issue by xomka686** [digitalocean/netbox#1194]
Hello, Jeremy!

Are there any plans to add ability to select different device naming options on the rack layout display (on the Racks -> Rack Elevations -> <Rack Name>) page?

This is useful when exporting rack layout to a 3rd party like remote hands as they are more familiar not with the devices hostnames, but rather their models.

I propose a name in the rack unit to be a list of options to be chosen by user like following:
- hostname (like now);
- hostname + model;
- just model.

Thanks!

**Comment by jeremystretch** [comment]
If you hover over the device, you should see a callout with its device type and role. It wouldn't be feasible to squeeze both the hostname and the make/model into the U view unless we make the entire elevation much larger. We don't currently have a mechanism for recording individual user preferences.

Somewhat related, #494 was opened a while back to show the asset tag instead of the model for unnamed devices.

**Comment by xomka686** [comment]
Ok, thanks, I've got the idea from #494.
Based on your answer I have one more proposal - if the model doesn't fit in the U description, will it be feasible to add a checkbox on a rack page like "show models" and it will pop-up the exact the same bubbles for each U as they're shown upon mouse-hover on the U, but for each unit? Also, this even can happen upon mouse-hover on the "Front" or "Rear" words on top of the rack.

Thanks!

**Comment by jeremystretch** [comment]
The current logic is to show the device's name if it has one; otherwise, the device's role is displayed. We used to fall back to displaying the make and model, but in many cases it didn't fit well into the limited space for 1U devices. I don't see much benefit in implementing more complex logic since the make and model are readily available by hovering the mouse over a device.

**Comment by xomka686** [comment]
Hello, Jeremy!

The only benefit in my proposal would be for guys, using "remote hands" service - where 3rd party company, unaware of your naming and models (sometimes, 
firewall, router and even server looks for them the same) makes physical movements in your rack and the amount of info they have directly influences the result - if your infrastructure is ruined by them or they do something useful.
That's why I find this useful when you can "screen shot" your rack with different naming or visualization options to provide this "remote hands" more info.

I've found one example from the openDCIM - they have an option to display a device's image in the Rack Unit and a button to switch between name and image, maybe that will be suitable for implement in the netbox.
ON the screen shot, labels are disabled and only device pictures show. Picture error is a typical not well-prepared demo :-)
![naming](https://user-images.githubusercontent.com/28758267/26873720-822fe236-4b83-11e7-983a-6309337c472a.jpg)
