### ISSUE TITLE
[Bug] Ports not included in API URLs

### ISSUE THREAD

**Issue by DerekTBrown** [digitalocean/netbox#1222]
### Issue type:
Bug 

**Python version:** Python 2.7
**NetBox version:** ee9b4f5d687e (v2.0-beta1)
(Running on Docker NetBox Build)

I am running NetBox on an irregular port (8001).  When I access the API endpoint (/api/), the port  isn't included in the URLs which are generated (ie `localhost/api/ipam/vrfs`), which is an invalid link.  The port should be present in these links.

**Comment by jeremystretch** [comment]
(Reposting my comment on #1184, which was closed due to lack of a response.)

The URLs for serialized objects are formed using Django REST Framework's [HyperlinkedIdentityField](http://www.django-rest-framework.org/api-guide/relations/#hyperlinkedidentityfield), which determines the host for the URL based on the incoming request. It looks like your httpd isn't forwarding information about the port it's running on to the WSGI service behind it.

If you're using nginx, try adding the following to your `location /` block:

```
proxy_set_header Host $host:8081;
```

We want to ensure we always return absolute URLs from the API to minimize the burden on the client.

Also, please be sure to upgrade to the current release (v2.0.3).

**Comment by DerekTBrown** [comment]
That resolved the problem! Thanks!
