### ISSUE TITLE
Custom fields for interfaces

### ISSUE THREAD

**Issue by jeanders** [digitalocean/netbox#1254]
### Issue type: Feature request

It would be very handy to have the ability to configure custom fields on interfaces as well. I am currently looking to store information such as if it is access or trunk, workstation or printer, etc.

**Comment by jeremystretch** [comment]
This has come up before, and it's been decided not to extend custom fields to interfaces. #150 will address VLAN assignment, and descriptions can be used to indicate the type of connected device (in lieu of creating a discrete connection).

**Comment by taktv6** [comment]
Seriously? Not supporting custom fields for interfaces unnecessarily limits the possibility to use netbox for automation purpose. Please fix. k thx bye.

**Comment by hypokondrickard** [comment]
it would be super useful here aswell. I'm building a services database where netbox is involved as a backend component. Because there is no way of "tagging" an interface with a service identifier and filter based on that via the API, I have to use a separate database to track what interfaces has been assigned the different services.

If it's been decided that custom fields on interfaces wont benefit mankind, could we still maybe make the /dcim/interfaces endpoint support filtering based on interface description?

Thanks a lot

**Comment by sirtux** [comment]
Hey @jeremystretch,

We have seen here 15 likes and 6 hearts for getting this feature - 
I understand if you don't have the ressources and time to implement this,
but would you be willing to accept a patch for this?

If so, we would be willing to sponsor a patch in the near future.

Thanks,
Tom

**Comment by jord-bh** [comment]
@sirtux @jeremystretch I would love to see this happen, it would open up a lot of automation capabilities revolving around interfaces. If I can be of any assistance be it testing or developing, I am also willing to put in some effort on this.

**Comment by reening** [comment]
Another +1 for this, for example I'd love to have the ability to add a custom boolean field to an interface  for a DHCP client. Other use cases could be interface/encapsulation types or tunnel endpoints. I don't like filtering based on names and using the global config context, since it is strongly tied to the interface. It is currently limiting in writing full automation using Netbox.

I'd also be happy to spend some hours implementing this if it will be accepted. It seems that there is quite some demand for a feature like this.

**Comment by sirtux** [comment]
We are working on this right now, and probably create a pull request and see if this is accepted, since the maintainers don't comment here right now. Stay tuned.

**Comment by jeremystretch** [comment]
This issue has been discussed and closed. Locking this thread.
