### ISSUE TITLE
Rack View Two Servers One U

### ISSUE THREAD

**Issue by MrEsL** [digitalocean/netbox#1267]
Hello,

I am researching  open source solutions for inventory managing of hardware devices in racks etc, and Netbox looks very promising.

We have a server that takes 2 U but has 4 servers/blades inside of it. is it possible to put two servers in a one U slot? or one server that takes 2 U but is divided into 4?

Attached is an image describing what I need.

Thank you very much.
![rack](https://user-images.githubusercontent.com/22653446/27131880-5546a2c2-5115-11e7-8cb8-f63723557fd7.jpg)

**Comment by jeremystretch** [comment]
NetBox allows you to create a parent device with device bays, and install child devices into these bays. Each child device is still managed as an independent entity with its own interfaces, IP addresses, etc. This is ideal for representing blade servers.

However, NetBox does not display the individual child devices in the rack elevation due to space constraints. (Longer device names would have to be extremely truncated.) The parent device is displayed in the rack elevation along with a count of populated and total device bays.

**Comment by jeremystretch** [comment]
Aside from the space constraint, there's also the matter of indicating how child devices would be displayed. For instance, suppose you have a parent device with four bays numbered 1-4. Should they be displayed like this?

```
+-----+-----+
|  1  |  2  |
+-----+-----+
|  3  |  4  |
+-----+-----+
```

Or like this?

```
+-----+-----+
|  1  |  3  |
+-----+-----+
|  2  |  4  |
+-----+-----+
```

Or like this?

```
+---+---+---+---+
| 1 | 2 | 3 | 4 |
+---+---+---+---+
```

IMO the extra logic needed to ensure the proper representation of a device isn't worth the gain of a minor convenience.

**Comment by MrEsL** [comment]
Thank you for clarifying the issue.
