### ISSUE TITLE
Errors on LLDP neighbors tab

### ISSUE THREAD

**Issue by tkald** [digitalocean/netbox#1281]
### Issue type: bug report

**Python version:** 2.7
**NetBox version:** 2.0.7

I get various popup alerts for different devices on LLDP neighbors tab, for example:

{"detail":"No RPC client available for this platform (Dell Idrac)."}
{"detail":"No IP configured for this device."}
{"detail":"No RPC client available for this platform (None)."}

**Comment by jeremystretch** [comment]
This tab should only be displayed if the device has all of the following:

1. A status of "active"
2. A primary IP assigned
3. A platform with an RPC client assigned

I'll fix it so that the LLDP tab is only displayed if all of these conditions are met. However, please note that RPC connectivity is not yet a supported feature (I'm hoping to get [NAPALM](https://github.com/napalm-automation/napalm) integration working soon).
