### ISSUE TITLE
Duplicate ip address using API

### ISSUE THREAD

**Issue by Atoms** [digitalocean/netbox#1285]
**Python version: 3.4
**NetBox version: 2.0.7

Have configured ENFORCE_GLOBAL_UNIQUE as True, in Frontend ip address is checked and cannot add duplicate ip_addresses, but using API you can still add duplicate ip address.

**Comment by jeremystretch** [comment]
The issue here is that Django REST Framework [no longer enforces a model's validation](http://www.django-rest-framework.org/topics/3.0-announcement/#differences-between-modelserializer-validation-and-modelform) through `clean()`. We'll need to either duplicate the validation logic in the serializer, or (more likely) call `clean()` from the serializer.

**Comment by jeremystretch** [comment]
Fixed in 1f9806a

**Comment by Dgcoy** [comment]
I may be missing something, but I am running the latest release and it looks like this issue may be back?
