### ISSUE TITLE
Inventory for Device Types

### ISSUE THREAD

**Issue by MrEsL** [digitalocean/netbox#1308]
Hello,

We have lots of Chassis servers that are "parents" and we attach to their device bays servers that are configured as children. 

Our problem is that we would like to add information to each of the children (cpu,ram,disks), the only way to do that is through adding inventory to each individual server.

Is there a way to add inventory to Device Types? that way each child will inherit the proper inventory.

Edit: On another topic.. I saw a issue someone opened regarding editing device types and it not updating current devices. Is this planned to be an option in the near future?

It doesn't make sense to build 100+ devices then adding an interface or the likes in the device type, and having to update each device individually.

Thank you.

**Comment by jeremystretch** [comment]
> Our problem is that we would like to add information to each of the children (cpu,ram,disks), the only way to do that is through adding inventory to each individual server.

NetBox isn't designed to function as an asset management system. While it has the ability to track device components for inventory purposes, it is primarily an IPAM/DCIM application. The inventory data is intended to be populated programmatically via the API or other means. It wouldn't make sense to define components like CPUs and hard disks under the device type, because you'll still need to glean unique data from each individual device.

> It doesn't make sense to build 100+ devices then adding an interface or the likes in the device type, and having to update each device individually.

It does make sense. You define all built-in console/power/interface components on the device type, which serves as a template for instantiating real devices. Then you can add removable components to those individual devices as appropriate. Also note that you can add components to devices in bulk.
