### ISSUE TITLE
support for vertical racks

### ISSUE THREAD

**Issue by tioan** [digitalocean/netbox#1310]
### Issue type: feature request

please add support for vertical racks like this one

![image](https://user-images.githubusercontent.com/259990/27773857-c63b4d44-5f83-11e7-839e-483944fd681d.png)

Rittal VerticalBox DK 7501.000

**Comment by jeremystretch** [comment]
This feature request lacks sufficient detail to be actionable. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md):

> When submitting a feature request on GitHub, be sure to include the following:
>
> * A detailed description of the proposed functionality
> * A use case for the feature; who would use it and what value it would add to NetBox
> * A rough description of changes necessary to the database schema (if applicable)
> * Any third-party libraries or other resources which would be involved

Please extend the request so that it meets all of  these requirements. If no response is received within a week, this issue will be closed.

**Comment by tioan** [comment]
I think on the Editing rack Site a new checkbox  "Vertical rack" like the "Descending units " checkbox is necessary.

![grafik](https://user-images.githubusercontent.com/259990/27949115-aaa7987c-62fc-11e7-9a8f-a541f2cfbca4.png)

If "Vertical rack" is activated please show under Rack and Rack Elevations an Rack with vertical Rack Units instead of horizontal Rack Units.

![grafik](https://user-images.githubusercontent.com/259990/27949984-f4ef273a-62ff-11e7-81f4-03619452c402.png)

**Comment by jeremystretch** [comment]
This seems like a very obscure requirement, and developing the markup/styling to render this type of elevation would require substantial effort. Given that you could alternatively just model it as a normal rack and add a note indicating that it's a vertical rack, I don't believe it's worth the investment of effort. But I'll leave this open for a while to see if anyone wants to take it on.

**Comment by Gelob** [comment]
What about just rotating the rack and resizing the width/height?

**Comment by bellwood** [comment]
@Gelob: do you mean for the visual/rack representation? If so, as stated, the CSS involved to do that would be a major PITA and add basically zero to little value (sorry)

As @jeremystretch stated, perhaps a flag to just notate the rack rail orientation is horizontal vs vertical would suffice but at the end of the day, just add a rack that is 5U high and keep trucking

90* of physical rotation in the real world shouldn't require any change within the software IMHO, since a 5U rack would obviously not be a standard cabinet

**Comment by jeremystretch** [comment]
I don't see any real benefit to adding a flag for this. A 5U rack is the same to NetBox whether it's standing up or on its side. Maybe this is a use case for free-form tags (#132).
