### ISSUE TITLE
Document installation using uwsgi as application host

### ISSUE THREAD

**Issue by darthmdh** [digitalocean/netbox#1335]
### Issue type: documentation

**Python version:**
**NetBox version:**

Running netbox under anything other than gunicorn is currently undocumented.  I've added simple steps to the web-server.md for using uwsgi as the app host instead & will include the pull request below.

I've currently kept it separate, though there's grounds to potentially merge the nginx configuration bits with the current nginx setup as essentially all that changes is which proxy function to use.

The setup is identical to the gunicorn example; nginx loads the static files and uwsgi takes the dynamic parts; I've also left out advanced config like high availability and caching as an exercise for the reader.

**Comment by jeremystretch** [comment]
I've limited the configuration docs to cover only gunicorn because it is sufficient to get an instance of NetBox up and running. Alternative applications (e.g. uWSGI) are supported but their configuration is [documented elsewhere](https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/uwsgi/). We want to avoid expanding the example installation in the documentation any further because it would increase the degree of time and effort to maintain the docs over time.
