### ISSUE TITLE
Make Inventory Items assigable.

### ISSUE THREAD

**Issue by netwavetech** [digitalocean/netbox#1423]
Inventory items need to be assignable like IP addresses.  We often will move RAM, CPU, Hard Drives around in servers as customer needs change.

Inventory should match devices in Layout.   So that we can preset Manfacture, Model #, etc.   

And then just as IPs are assigned to a device, should be able to assign to a device.   This way it would be easy to move inventory around without having to worry about mistypes (fat fingers)

**Comment by jeremystretch** [comment]
Technically, InventoryItems are reassignable via the API; we just don't provide a UI function for it. This is because we try to keep NetBox out of asset management territory. For instance, NetBox does not provide a mechanism for tracking spare items: An item is either installed in a device, or (as far as NetBox is concerned) it doesn't exist. If you need more robust asset management functionality than what NetBox offers, I suggest adopting a tool built specifically for that purpose and leaving inventory data out of NetBox.
