### ISSUE TITLE
Custom fields for rack groups

### ISSUE THREAD

**Issue by flowdnb** [digitalocean/netbox#1441]
### Issue type
[x] Feature request 

### Environment
* NetBox version:  2.1.2

### Description
We use rack groups to group racks within a site by room. It would be useful to configure custom fields on rack groups as well to store extra information such as room number, locking info, floor level.

**Comment by jeremystretch** [comment]
This has come up before, so I've added a [section in the FAQ](https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models) for it. The short answer is that we don't associate extra data with organizational models because they don't have dedicated views, and including custom fields in a list view incurs a substantial performance penalty.
