### ISSUE TITLE
Error: <class 'django.urls.exceptions.NoReverseMatch'>

### ISSUE THREAD

**Issue by aveloz** [digitalocean/netbox#1442]
After upgrading Netbox to the latest version Im getting this error:

`<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'rack_elevation_list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []`

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!
