### ISSUE TITLE
FR: When adding devices to the Rack Elevation, have the option to select from existing devices.

### ISSUE THREAD

**Issue by traveler3468** [digitalocean/netbox#1450]
I was thinking that it would be nice to have the ability to select from existing devices in NetBox when adding a device from the rack elevations view. I think the devices would show up in a drop down list and be filtered based in the tenant/site that the rack belongs too. This would allow for devices to be created and tracked in NetBox before they were racked and also allow the ease at which devices are added to the rack space. 

 Thoughts?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!
