### ISSUE TITLE
feature: reference graphs through API to remote system with token

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1456]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  2.1.3

### Description
A number of monitoring and graphing systems make available device/port graphs through an API rather than a direct unauthed URL. It would be helpful to be able to reference these graphs using an API call with a token to improve on the graph integration. 

Having said this, sometimes it is also necessary to to pull the graph information from multiple sources depending on the device being referenced. Based on the current implementation there isn't a way to set a specific graph template per customer/site.

**Comment by jeremystretch** [comment]
This was [discussed on the mailing list](https://groups.google.com/forum/#!topic/netbox-discuss/h7HAIPbylUo) recently. Because the graphs are embedded using `<img>` tags, there is no mechanism available for sending an authorization header with the request. It might be possible with an AJAX request but you have to jump through some hoops to embed the retrieved image and I'm not interested in going down that path.

> Having said this, sometimes it is also necessary to to pull the graph information from multiple sources depending on the device being referenced.

The embedded graphs were only ever meant to be a convenience feature. If you have a single NMS with no or basic authentication, great. If not, it won't fit your needs; #969 should provide a better solution in that case.
