### ISSUE TITLE
Issue selecting multiple IP addresses for bulk edit

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1471]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  2.1.4

### Description
When selecting multiple IP addresses to be bulk edited, it returns that no addresses have been selected.
First tick the option for all addresses on the page.
Accept that it will tag all available addresses.
Selected EDIT.

1. 
![image](https://user-images.githubusercontent.com/16985649/30022899-9dbda044-916d-11e7-96b2-9e60d4d1960e.png)

2.
![image](https://user-images.githubusercontent.com/16985649/30022909-ab882bd6-916d-11e7-8362-e3fbab0bbb08.png)

**Comment by darkstar** [comment]
On which page do you try this? It works for me both on the "IP Space"->"IP Addresses" page as well as on the "IP Space" -> "Prefixes" -> (any prefix) -> "IP Addresses" tab/page.

But I also don't see the additional checkbox "Select all $n items" in any of these that you showed in your screenshot. Does this only show up if you have over a certain number of IPs listed?

**Comment by Bill-Irvine** [comment]
Ive seen this aswell on the prefixes tab.

 /ipam/prefixes/1/ip-addresses/

**Comment by InsaneSplash** [comment]
@darkstar Yup, you will need more than 1 page of IP addresses in the list you are going to be making changes too.

**Comment by jeremystretch** [comment]
@InsaneSplash I cannot replicate this issue on the IP address list. What URL are you going to?

**Comment by InsaneSplash** [comment]
Its the list of addresses attached to a child prefix (/24). I select the option to select all 160 addresses for example, then click edit, the page then returns with the no selected addresses error.

```
example:
http://netbox/ipam/prefixes/4/ip-addresses/
```

**Comment by jeremystretch** [comment]
I'm not able to replicate this. Could you please provide the exact steps needed to replicate, beginning with the creation of a parent prefix?

**Comment by Bill-Irvine** [comment]
Hi,

So it looks like this is only an issue when there is more than that one page(i.e multiple pages of IP addresses needing selecting). Selecting the IP addresses on one page and editing them does not have the same issue.

It also does not happen on the Global IP addresses page https://netbox/ipam/ip-addresses/

My guess is that it might be an issue with the Prefix being assigned to a VRF.

1. Create Parent IPV6 Prefix (in my case its a /118
==Prefix==
Status: Active
VRF: Assigned
Role: Unassigned
"Is a pool": True
==Site/Vlan Assignment==
Site: unassigned
VLAN Group: Unassigned
VLAN: Unassigned
==Tenancy==
Tenant Group: Assigned
Tenant: Assigned

2. Attach these addresses so that you have more than one page assigned (my default Pagination is set to 50)

3. Goto your prefix URL (in my case https://netbox/ipam/prefixes/1/)

4. You will see that it displays the Prefix within the VRF

![prefix-vrf](https://user-images.githubusercontent.com/5893433/31198574-43fb613e-a9b1-11e7-9979-b2a858490ca0.PNG)

5. select the IP address Column to select all on the page, it then displays the "Select all 516 items matching query"

Select this and hit "Edit All"

![image](https://user-images.githubusercontent.com/5893433/31198663-86d8aac0-a9b1-11e7-9f4b-0935be0d4344.png)

This is when the "No IP addresses selected appears"

Let me know if you need anything more

**Comment by InsaneSplash** [comment]
Looks like you have tracked it down.
