### ISSUE TITLE
Support For Logical "GRE Tunnels" Similar to Logical "Link Aggregation Groups"

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1538]
### Issue type
[X] Feature request 

### Environment
* Python version: 2.7.12
* NetBox version: 2.1.4

### Description
On all network platforms (`ios`, `junos`, `aos`, etc), when creating a GRE tunnel, you must specify the "source" of that traffic.  With the current state of the NetBox ORM, this is not possible.

I'd like to request that a new `Virtual` type of interface be created to serve as the "source" of the `child` GRE interface (similar to how a logical `Virtual` interface type of `Link Aggregation Group` can be associated as a `parent` interface to physical `child`).

This can currently be done by creating a parent `LAG` interface type that **_pretends_** to operate as the tunnel source, however, this is not "correct" per-say and it also has the limitation of not allowing other "virtual" interfaces (such as "Loopbacks" as is commonly done for GRE interfaces) to act as the child interface.

While I'm not well-versed in DB schemas, I don't think any **major** changes would need to be done to support this request as it can _kind of_ already be done (as was mentioned previously).

I don't believe this request will be limited to my specific scenario because, as the popularity of NetBox grows, others will need similar `parent` / `child` relationships for interfaces that aren't tied to the current requirement of the `child` being a physical interface.

If needed, the new interface type can be named more generically than `GRE` or `Tunnel` so that it can applicable to different scenarios.  Alternatively, the current implementation of `LAG` interfaces can be altered to just be a `parent` interface with associated `child` interface(s).

I'm definitely open to a discussion taking place concerning this request.

**Comment by jeremystretch** [comment]
I've left this feature request open for a few weeks for others to comment, but it doesn't seem to have drawn much interest. My take is that modeling tunnel interface relationships is out of scope for NetBox. Unlike LAGs, they are wholly logical constructs. While I understand that there would be value in attempting to model them in NetBox, doing so would step firmly into general configuration management territory, which we want to avoid.

Tunnel interfaces can be represented as normal virtual interfaces and assigned IP addresses; they just can't be mapped to physical source interfaces.

**Comment by ossark** [comment]
+1 on this one. 

Tunnel interfaces can indeed be represented as virtual interfaces. It is the connection I would like to see represented in netbox. So far I have used "cables" to connect them but that does obviously not work for virtual machines. Any suggestions on how to remedy this problem? Is this a sufficient use case in order to have a proper tunnel/gre representation in netbox? 

As it is possible to connect virtual interfaces on devices with a cable in netbox can we also have the ability to connect virtual interfaces in virtual machines with cables?

**Comment by alexjhart** [comment]
I’m looking to model tunnels with virtual machines as well. Current use case is showing a GRE tunnel connection between a physical device and a cloud VM. This is applicable to netbox because of the IPAM offerings (IP, prefix, vrf, etc). I don’t see a reason not to offer virtual cable type and connections between physical and virtual interfaces.
