### ISSUE TITLE
Allow for module/part manufacturers

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#157]
Examples where module/parts manufacturer are different from the chassis:
* Optics/twinax/DAC in NICs
* Server NICs (SolarFlare, Intel, etc.)

**Comment by puck** [comment]
Also, modules and parts can add more ports.

**Comment by jeremystretch** [comment]
Modules were originally intended to store information gleaned through automated inventory, e.g. `show inventory` (Cisco IOS) or `show chassis hardware` (Junos). AFAIK it's not possible to determine a vendor this way, so that wasn't added as a field.

I think it makes sense to add an optional `manufacturer` field to the Module model. Should this be tied to the Manufacturer model (as DeviceTypes are) or a freeform text field?

**Comment by ryanmerolle** [comment]
I would tie it to manufacturer model.  Free form allows for mistakes.  From an inventory / search I'd want to be able to find out how many of a x model in an environment when it comes to recalls or upgrades.

**Comment by laetrid** [comment]
Is there a way to import `show inventory` into the device inventory via web interface (similar to device CSV import)?
