### ISSUE TITLE
extras_useraction to log remote_addr

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1571]
### Issue type
[X] Feature request 

### Environment
* Python version:  3.5.2
* NetBox version:  2.1.5

### Description

In the `extras_useraction` table it would be helpful to have an extra column recording the [client IP address](https://stackoverflow.com/questions/4581789/how-do-i-get-user-ip-address-in-django).

Use case:

* some people have been logging in as `admin` instead of their personal account, and need to identify who did what

**Comment by jeremystretch** [comment]
> some people have been logging in as admin instead of their personal account

Well, that's easy to fix. Get rid of the shared `admin` account (any account can be designated as a superuser) and use only individual accounts. Logging the IP address of a request would not definitively identify an individual anyway.

I'm going to reject this request because I'm planning to overhaul and improve the activity log in the near future (see #1127).
