### ISSUE TITLE
Topology Maps:  There was an error generating the requested graph. Ensure that the GraphViz executables have been installed correctly.

### ISSUE THREAD

**Issue by omen89** [digitalocean/netbox#1583]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  2.1.6

### Description
Hello! 

Error when opening some "Topology Maps" -> There was an error generating the requested graph. Ensure that the GraphViz executables have been installed correctly.

In stderr log: 
dot: class2.c:104: make_chain: Assertion `(((Agedgeinfo_t*)(((Agobj_t*)(orig))->data))->to_virt) != ((void *)0)' failed.

[root@server~]# pip show graphviz
Name: graphviz
Version: 0.8
Summary: Simple Python interface for Graphviz
Home-page: https://github.com/xflr6/graphviz
Author: Sebastian Bank
Author-email: sebastian.bank@uni-leipzig.de
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires:

**Comment by candlerb** [comment]
You have a bad / corrupt version of Graphviz.  Type `dot -V` at the command line to see what version you have.

I use graphviz package 2.38.0-12ubuntu2.1 under Ubuntu 16.04 and it's fine.

**Comment by jeremystretch** [comment]
If you need further assistance, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by omen89** [comment]
Thank you! I`m add official repo Graphviz for my CentOS 7 and update to version 2.38.0. And all fine, topology maps work!

**Comment by KempWatson** [comment]
I'm getting this too, on CentOS. dot -v says everything is fine, Graphvis 2.30 latest

**Comment by EduardoFarias04** [comment]
hello

i have this error, but my system in netbox is 2.3.5, python 3.6.3 and graphviz 2.30.
later the make upgrade continue with the Error when opening some "Topology Maps" -> There was an error generating the requested graph. Ensure that the GraphViz executables have been installed correctly.

sorry my English, pls help me!

**Comment by candlerb** [comment]
> graphviz 2.30.

Too old. Upgrade to 2.38.0

**Comment by EduardoFarias04** [comment]
i maked update for 2.38.
But continue with the error : here was an error generating the requested graph. Ensure that the GraphViz executables have been installed correctly.

pls help, a light.

**Comment by candlerb** [comment]
I think you need to read http://www.catb.org/~esr/faqs/smart-questions.html#intro

It works for everyone else, but not for you.  Therefore the problem is likely to be at your side.  We are not in front of your computer, so you need to look for information to diagnose the problem, or else we cannot help you.

Firstly, you haven't even said what OS you are running under.  Then you didn't say where you got the updated graphviz package from, or how you installed it.  How sure are you that you upgraded it correctly? What does `dot -V` show?  You haven't looked for any logs.

Try running netbox in its local debugging webserver.  Edit `/opt/netbox/netbox/netbox/configuration.py`, change `DEBUG = False` to  `DEBUG = True`, then start server like this:

```
python3 manage.py runserver '[::]:8000' --insecure --noreload
```

Point browser at http://yourmachine:8000/

Do whatever causes the error, then copy-paste what you get from the web server session.

**Comment by andreitoupinets** [comment]
Hi,
I had same problem, DEBUG=True doesn't help. 
It's default error for every failed call of tmap.render(img_format=img_format) in file extras/api/views.py

So, when I move this call out from try/except block, I found source of problem from normal django exception, it was wrong regex in device pattern.

**Comment by jeremystretch** [comment]
I'm locking this thread. GitHub issues are for development only. Pleaese use the mailing list for support problems as I instructed above.
