### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TimCook1** [digitalocean/netbox#1617]
Two issues I've seen.

On the webserver install page under nginx you have (http://netbox.readthedocs.io/en/stable/installation/web-server/):
# ln -s /etc/nginx/sites-available/netbox

Should be:
# ln -s /etc/nginx/sites-available/netbox default

On the page for generating a secret key on the netbox page (http://netbox.readthedocs.io/en/stable/installation/netbox/):
Under creating the secret key, it tells you to run:
netbox/generate_secret_key.py

This file at the top directs you to /usr/bin/env python - on ubuntu using python3, this doesn't work.  It should be /usr/bin/env python3.  Given that python3 is the recommendation at this point, I would assume the file should be updated, or somewhere in the steps we should be doing an ln -s python3 python.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!
