### ISSUE TITLE
Filter suggestions based on device "content"

### ISSUE THREAD

**Issue by thefreakquency** [digitalocean/netbox#1628]
### Issue type
[ x ] Feature request 

### Environment
* Python version:  3.5.4
* NetBox version:  2.2.1

### Description
When connecting a device, let's say a Server to a PDU, using the Search capability, devices returned in suggestions are all showing. It would be interesting to filter them to remove those who have no corresponding connectivity declared (ie: if a device has no power port, it should not show up in the suggestion list when connecting a power device... Same logic should then would be applied for networking and console.

A similar scenario would be in a page like "Add a new device", where all declared manufacturers would show up even if there are no Device Type created for some of the manufacturers. It would make the interface less loaded and easier to use if non relevant information was filtered. 

Another scenario would apply to us, but I'm not sure if this would apply by default is that a Device type categorized as "Child" should not be suggested when adding devices to a rack.

**Comment by jeremystretch** [comment]
This could result in very confusing behavior. We don't want to omit objects from a list unless the user knows why they're being omitted, and we don't have a way of expressing that when populating a selection field. For instance, if a user is expecting to find a certain device which has been silently omitted because it's missing a particular component, they're left wondering why the device isn't showing up. The more transparent approach is to allow them to select the device, and quickly realize that it's missing a particular component, which is easily resolved.

**Comment by thefreakquency** [comment]
Based on the logic applied when you try to assign a child device to a device bay where only suitable devices are being showed (Child devices must first be created and assigned to the site/rack of the parent device.), I would say this feature request would provide a more coherent than confusing behavior. 

Having no listing filtering provide a crowded interface that can lead to misselection by the user especially when the device nomenclature is not ideal... 

I have the feeling the device definition (from the device types definition & modification) should drive the whole behavior. If it's not there in the list, the user can always go back to the device page and ensure it has the proper connection definitions instead of being proposed superfluous choices... 

Could this "filtering" be proposed as an on/off option if we cannot convince everybody? :)

**Comment by thefreakquency** [comment]
@jeremystretch , based on my last comment can this be reevaluated?
