### ISSUE TITLE
IP address API endpoint triggers excessive database queries, resulting in poor performance

### ISSUE THREAD

**Issue by afics** [digitalocean/netbox#1645]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.2
* NetBox version:  2.2.1

### Description

Certain API calls produce more SQL queries than they have to which results in those calls being "slow".
Example:
```
200 GET
/api/ipam/ip-addresses/?limit=10000
12106ms overall
2305ms on queries
2374 queries
```
This is fixed by #1535. While the Pull request is for an older version of Netbox, the newest version is also affected by this problem.
The same API call after applying the patch:
```
200 GET
/api/ipam/ip-addresses/
3215ms overall
255ms on queries
8 queries
```

**Comment by jeremystretch** [comment]
The IP address serializer embeds the full serializer for the related interface rather than a nested serializer as in other cases. This was done to ensure the parent device was included as well but was probably a mistake. We can implement a slightly extended nested serializer to ensure only the necessary interface details are included. This would remove the need to extend the database query.
