### ISSUE TITLE
Aggregate with VRF support

### ISSUE THREAD

**Issue by wanglf** [digitalocean/netbox#1686]
### Issue type
[x] Feature request
[ ] Bug report 
[ ] Documentation   

### Environment
* Python version:  3.4.5 
* NetBox version:  Example: 2.2.4

### Description
In IPAM module, both ip address and prefix have a VRF field. Since ip address belong to prefix and prefix itself belong to aggregate, it will be helpful for aggregate to have a VRF field either.

Currently if ip prefixes from different VRF overlap, it will difficult to distinguish in aggregate view.  And in private corporate network, same aggregate might be assigned by different RIRs.

**Comment by jeremystretch** [comment]
Prefixes don't really "belong" to aggregates. The purpose of defining aggregates is simply to establish the root level of the IP space hierarchies (v4 and v6). They provide a mechanism for defining the scope of your IPAM to show only the portions of the global address space in which you're interested (as opposed to starting from 0.0.0.0/0). It's also perfectly acceptable to have prefixes which are not covered by any aggregate (e.g. circuits numbered with provider-owned IPs).

There's no concept of VRF assignment at the root of the hierarchy because it would result in redundant objects. For instance, you might have a hundred VRFs addressed out of the 10.0.0.0/8 space; you would not want a hundred instances of 10.0.0.0/8 in the aggregates list.

**Comment by hzwlf2002** [comment]
If aggregate only take `global address space` into account,  I get your point.

But when I define an aggregate 10.0.0.0/8 and a prefix 10.0.0.0/16 which is put into a vrf(not default global).  The latter one will be counted as prefix numbers and utilization in aggregate 10.0.0.0/8.  Sometimes this can be confusing.
