### ISSUE TITLE
Logout doesn't clear private session key for secrets

### ISSUE THREAD

**Issue by evantheenginr** [digitalocean/netbox#1740]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.5
* NetBox version:  v2.2.6

When logging out the session key a user is making use of and has entered is not cleared.  It should be cleared when a user logs out.

I have 2 users "admin" and "named user."  Using a single browser (Firefox) and having logged in as "admin" and performing a number of actions related to secrets including an import and then after logging out and logging back in as a different user (my own "named user") the problem is observable in that I am not asked for my key when trying to unlock a secret.  I am greeted with a prompt (browser alert) stating ["Invalid session key."].

Note that the area on my "named user" profile after logging out from my "admin" session where the "Delete session key" button is simply shows "No session key" and I am not able to clear out the session key unless I log out of my own "named user" account and log back in as "admin".

**Comment by Tangeek42** [comment]
I noticed the same thing yesterday while installing (for the first time). I thought this was intended and the Session Key was representing the browser/device in itself ? Note that I don't know any details about it, I just noticed that I encountered bugs only since I changed logins, so I thought this was it.

If it's a bug, I report it as well on Netbox 2.2.6 and Python 3.4.2.
