### ISSUE TITLE
Aggegrate Custom Fields per Rack

### ISSUE THREAD

**Issue by Phhere** [digitalocean/netbox#1747]
### Issue type
[ x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5
* NetBox version:  2.2.6

### Description
It would be nice to have an option to aggregate values of all devices inside a rack.
Example: 
Power usage of Device: Sum of Power usage inside the rack
Numer of required ports: Count of required ports on patchfield

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. It looks like your feature request is missing some information. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md), please ensure that you have provided all of the following:

* A detailed description of the proposed functionality
* A use case for the feature; who would use it and what value it would add to NetBox
* A rough description of changes necessary to the database schema (if applicable)
* Any third-party libraries or other resources which would be involved

Please update the issue so that it meets all of  these requirements. If no response is received within a week, this issue will be closed. Thanks!

**Comment by Phhere** [comment]
Detailed Description:
This feature would give an overview of attributes aggregated per rack. It should be possible to add a aggregation function for some attributes and custom attributes to a rack which will take all entities inside the rack as input.
Example: count(PowerOutles), sum(Custom_Attribute_Watts)

Use Cases:
It could be used for rack planing / reservation to see how many rj45 / sfp / qsfp - ports are required on an toplevel rack switch.
It can be used to calculate the required power usage of a rack by summing up all power values of individual components inside the rack.
It can be used to count required power outlets / plugs per Rack.

Database Changes:
Not required

Third-party libraries.
Not required

I hope these information help you

**Comment by jeremystretch** [comment]
This wouldn't really be practical to implement. NetBox doesn't know the purpose of a custom field, only it data type. Some metrics make sense to aggregate whereas others don't. Attempting this natively in NetBox would result in a lot of gargbage data (and probably a good bit of overhead). You're better off using the API to pull exactly what data you want from NetBox in an intelligent manner.
