### ISSUE TITLE
Custom Field and Allow Import To Custom Field

### ISSUE THREAD

**Issue by hmmxp** [digitalocean/netbox#1750]
### Issue type
[Y] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4
* NetBox version:  2.2.6

### Description

Default Add a new circuit have the following fields:

Circuit
- Provider
- Circuit ID
- Type
- Activation Date
- Commit rate (Kbps)
- Description

Tenancy
- Tenant group
- Tenant

Currently have added custom fields such as contract end date. MRC and such.

As we have a lot of circuits and having the additional custom fields will allow for us to manage the circuits with ease, to use Circuit import function to import all the circuit information including both the default fields and custom fields.

**Comment by vmisson** [comment]
+1

**Comment by avisom** [comment]
+1

**Comment by s0liddi** [comment]
+1

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. It looks like your feature request is missing some information. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md), please ensure that you have provided all of the following:

* A detailed description of the proposed functionality
* A use case for the feature; who would use it and what value it would add to NetBox
* A rough description of changes necessary to the database schema (if applicable)
* Any third-party libraries or other resources which would be involved

Please update the issue so that it meets all of  these requirements. If no response is received within a week, this issue will be closed. Thanks!

**Comment by jeremystretch** [comment]
Closing this issue as it does not meet the standards listed above. See #1844 for other discussion regarding the import of custom fields.

**Comment by Here2Tinker** [comment]
Hello,

Newbie here, GitHub and NetBox wise so please be patient, I am just getting to know the community and the product. :-) 

As proposed, I have seen #1844 but it's about migrating custom fields between different instances of NetBox - where as my perdicament is centered around importing a lot of information from a CSV file. 

So far I've tested it on our NetBox (version v2.4.3) by using the standard import column headers: 

_device_role,manufacturer,model_name,status,site_

This works fine.


Then, I have added several custom fields for Devices and extended the column headers accordingly:

_device_role,manufacturer,model_name,status,site,**management_ip,environment_tag,business_impact,pci_device,tech_owner**_

However, the test import fails as soon as it reaches the 1st custom field name:
**Unexpected column header "management_ip" found.**

Do I need to provide more details in the column headers? Like, database table holding the custom fields so it doesn't query the default one?

Please find below the issue details, to the best of my knowledge:

- Detailed description of the proposed functionality
  Possibility to add through UI all the pre-created custom fields to column header (for Devices import)
- Use case for the feature; who would use it and what value it would add to NetBox:
  Easier import od devices from 3rd party CMDB 
- A rough description of changes necessary to the database schema (if applicable)
  None required, I think?
- Any third-party libraries or other resources which would be involved
  Also, none?

Regards,
Igor
