### ISSUE TITLE
Interface Form Factor UI

### ISSUE THREAD

**Issue by Phhere** [digitalocean/netbox#1753]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   
### Environment
* Python version:  3.5.3
* NetBox version:  2.2.6

### Description

Add Interface to create new Form Factory or add Form Factor for Infiniband

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. It looks like your feature request is missing some information. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md), please ensure that you have provided all of the following:

* A detailed description of the proposed functionality
* A use case for the feature; who would use it and what value it would add to NetBox
* A rough description of changes necessary to the database schema (if applicable)
* Any third-party libraries or other resources which would be involved

Please update the issue so that it meets all of  these requirements. If no response is received within a week, this issue will be closed. Thanks!
