### ISSUE TITLE
Child Prefix Tab on Prefix page

### ISSUE THREAD

**Issue by awfki** [digitalocean/netbox#1773]
### Issue type
[X ] Feature request 

### Environment
* Python version: 2.7
* NetBox version: 2.2.4

### Description
On the page for a Prefix (https://netbox/ipam/prefixes/7/) there are tabs for Prefix and IP Addresses.  Please add an additional tab called "Child Prefixes" between those.  The new tab should just link to the Child Prefixes table further down the same page.

[Screenshot with arrows showing what I intend.](https://cl.ly/2M0I24273e1j)

Reason is that dependent on window size the Child Prefixes list is often hidden so if the user doesn't know it's there they may jump into IP addresses and then wonder why the child prefix doesn't show up.  

I don't believe any DB changes or library updates are needed.

**Comment by awfki** [comment]
Looking at whether I could solve my own problem and it looks like the HTML for the prefix page is here ([prefix.html](https://github.com/digitalocean/netbox/blob/252be84bf07a27868c9e5548558834b2fd62e3d8/netbox/templates/ipam/prefix.html)) but it references prefix_header.html and I don't see that file anywhere.

If someone want to point it out I'll be happy to take a look and see if I can submit a PR. I haven't played with Django at all so it's very possible that it would be beyond me.

**Comment by ajaydeepsingh** [comment]
It's possible. Just add another tab to the top and instead of linking to a different page, just have that new tab link to the start of the Child Prefixes section.
![screen shot 2017-12-14 at 1 21 01 pm](https://user-images.githubusercontent.com/22304991/34007942-a9127a38-e0d1-11e7-9e27-65454533ba2a.png)

To get the new tab:
`<li role="presentation"><a href="#child">Child Prefixes</a></li>`

and then just add an id tag to that portion of the generated page:

`<div class="col-md-12" id="child">`

**Comment by jeremystretch** [comment]
I originally added the child prefixes list to the main prefix view so that users wouldn't have to make a second request to view the children, but I like the idea of standardizing on using separate views for related objects.
