### ISSUE TITLE
API support for power connections

### ISSUE THREAD

**Issue by sirtux** [digitalocean/netbox#1788]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* NetBox version:  2.2.6

### Description

We noticed that the API in 2.2 is missing write functions for power connections,
is this on purpose?

Is somebody already working on this, or is a merge request at a later point appreciated?

Thanks,
Tom

**Comment by jeremystretch** [comment]
@sirtux What are you trying to do? What is the request being made to the API?

**Comment by sirtux** [comment]
I want to connect a power port to a power outlet via API,
and I don't see a /api/dcim/power-connections POST support, only GET. If I try a post I get afair a 405 error.

I'd like to see the same featureset as a post on /api/dcim/interface-connections.

**Comment by jeremystretch** [comment]
Ah. Interface connections are modeled differently than console and power connections due to their bidirectional nature: There's a discrete`InterfaceConnection` model which represents a connection between two interfaces. Console and power connections, however, use the `ConsolePort` and `PowerPort` models to define connections.

What you want is the `/api/dcim/power-ports/<id>/` endpoint. A PATCH request to this endpoint lets you define a connected `power_outlet`:

```
$ curl -X PATCH -H "Authorization: Token <token>" -H "Content-Type:application/json" -H "Accept: application/json; indent=4" http://localhost:8000/api/dcim/power-ports/2891/ --data '{"power_outlet": 44569}'
{
    "id": 2891,
    "device": 1599,
    "name": "PSU0",
    "power_outlet": 44569,
    "connection_status": true
}
```
