### ISSUE TITLE
Return nested representations of related objects when modifying an object via the API

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1794]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6
* NetBox version:  2.2.8

### Description

When I request virtual interfaces, the `virtual_machine` field is expanded to include the VM's details.
But when I PATCH a virtual interface, the `virtual_machine` field is simply the id of the VM.

**GET http://netbox-frontend.ninevirt.docker/api/virtualization/interfaces/13/:**

```
{
    "id": 13,
    "name": "eth0",
    "virtual_machine": {
        "id": 4,
        "url": "http://netbox-frontend.ninevirt.docker/api/virtualization/virtual-machines/4/",
        "name": "development-root-v3-xenial"
    },
    "enabled": true,
    "mac_address": "52:54:00:B5:BC:74",
    "mtu": null,
    "description": ""
}
```

**PATCH http://netbox-frontend.ninevirt.docker/api/virtualization/interfaces/13/:**

```
{
    "id": 13,
    "name": "eth0",
    "virtual_machine": 4,
    "enabled": true,
    "mac_address": "52:54:00:B5:BC:74",
    "mtu": null,
    "description": ""
}
```

**Comment by jeremystretch** [comment]
This happens because we're using separate read and write serializers for most endpoints. (The write serializer allows for setting related fields using only a primary key, whereas the read serializer returns a nested representation of the related object.) I'd love to consolidate these functions into a single serializer for each object, but haven't found a practical way to do so yet.
