### ISSUE TITLE
Default tenant view

### ISSUE THREAD

**Issue by notsamuk** [digitalocean/netbox#1808]
Please can we have an option to select a Tenant that is persistent while using the site so when we browse between pages it maintains that search filter rather than having to set the filter each time.

Apologies if already on here, could not see on search.

Thanks
Sam

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!
