### ISSUE TITLE
HTML Drag and Drop

### ISSUE THREAD

**Issue by bvessey** [digitalocean/netbox#1872]
[X ] Feature request 

Could HTML drag and drop be added to the web interface when adding attachments.

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/File_drag_and_drop

Ideally with the option of uploading multiple attachments / photos at once.

**Comment by cyberjacob** [comment]
[Dropzone](http://www.dropzonejs.com/) appears to be a popular way of doing this, which just needs an AJAX endpoint to send the files to.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. It looks like your feature request is missing some information. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md), please ensure that you have provided all of the following:

* A detailed description of the proposed functionality
* A use case for the feature; who would use it and what value it would add to NetBox
* A rough description of changes necessary to the database schema (if applicable)
* Any third-party libraries or other resources which would be involved

Please update the issue so that it meets all of  these requirements. If no response is received within a week, this issue will be closed. Thanks!
