### ISSUE TITLE
Multiple Disks

### ISSUE THREAD

**Issue by aarjbdea** [digitalocean/netbox#1887]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.5
* NetBox version:  2.3.0-dev

### Description
On a virtual machine, it would be useful to have the ability to add multiple disks and then have a counter of "Total Disk" that is a sum of disks 1-n

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. It looks like your feature request is missing some information. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md), please ensure that you have provided all of the following:

* A detailed description of the proposed functionality
* A use case for the feature; who would use it and what value it would add to NetBox
* A rough description of changes necessary to the database schema (if applicable)
* Any third-party libraries or other resources which would be involved

Please update the issue so that it meets all of  these requirements. If no response is received within a week, this issue will be closed. Thanks!

**Comment by aarjbdea** [comment]
Currently on a Virtual Machine you can state the vCPU, Memory & Disk sizes, Currently it is one integer for all disk size for that VM, I propose that instead by default there is "Disk1" where you enter the size in GB with the ability to add more disks to that VM where you would also enter the size of that disk in GB, the "Disk" field would instead be a SUM of the disks whether it be 1 disk or 10 disks. 

When deploying virtual machines we are given requirements of having multiple disks on a VM and each disk can be different sizes. This would help show a more detailed view of how the disks are sized on a VM. For Example

**Total Disk - 350 GB
Disk 1 - 100GB
Disk 2 - 150GB
Disk 3 - 75GB
Disk 4 - 25GB

Not sure on the database part and do not believe 3rd party libraries or other resources are required for this

**Comment by jeremystretch** [comment]
This feels like it's creeping out of scope for NetBox. NetBox's primary function is to manage network infrastructure, not end hosts. The CPU/memory/disk fields were included on the VirtualMachine model merely as a convenience for those who choose to use them. Introducing new models to support the addition of individual components puts us squarely into VM orchestration territory, opening the door for further creep.

I suggest using the provided field to indicate the aggregate amount of disk available to the VM, and defer to whatever orchestration system you have in place for component details.
