### ISSUE TITLE
Virtual Chassis and Search filter (Rack group,...)

### ISSUE THREAD

**Issue by GitRost** [digitalocean/netbox#1973]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 2.xx 
* NetBox version: 2.3.1 

### Description
Poor Search filter in Virtual Chassis section.
No Rack group, no Manufacturer, ...

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. It looks like your feature request is missing some information. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md), please ensure that you have provided all of the following:

* A detailed description of the proposed functionality
* A use case for the feature; who would use it and what value it would add to NetBox
* A rough description of changes necessary to the database schema (if applicable)
* Any third-party libraries or other resources which would be involved

Please update the issue so that it meets all of  these requirements. If no response is received within a week, this issue will be closed. Thanks!

**Comment by GitRost** [comment]
![image](https://user-images.githubusercontent.com/19433257/37697017-74113174-2ceb-11e8-835b-c4a3d4bf1eb1.png)
No Rack group, no Manufacturer.

**Comment by GitRost** [comment]
And one more thing.
I do global search, got list needed devices but can not select them to create Virtual Chassis
