### ISSUE TITLE
Circuit and related prefixes view

### ISSUE THREAD

**Issue by PeepOks** [digitalocean/netbox#1991]
### Issue type
[x] Feature request 
[ ] Bug report
[ ] Documentation 

### Environment
* Python version:  2.7.5
* NetBox version:  2.3.1

### Description
We would like to view what network prefixes are provided by what circuit. This info would help us to find Provider/ISP more quickly when it is needed. Some Circuits can have many prefixes related to them
I don't know if this is supported by a current database schema.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. It looks like your feature request is missing some information. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md), please ensure that you have provided all of the following:

* A detailed description of the proposed functionality
* A use case for the feature; who would use it and what value it would add to NetBox
* A rough description of changes necessary to the database schema (if applicable)
* Any third-party libraries or other resources which would be involved

Please update the issue so that it meets all of  these requirements. If no response is received within a week, this issue will be closed. Thanks!

**Comment by PeepOks** [comment]
We have many circuits where ISP provides us multiple L2 uplinks and we have 2 routers(for redundancy) what use same circuit. I have a problem when I want to add both routers uplinks to circuit. In circuit configuration only one A side termination is allowed.
Current solution works best if ISP provides L3 uplinks.

If circuit and network prefix relation would exist then we can know what circuit or ISP provides us specific public network prefix.

**Comment by jeremystretch** [comment]
Circuits can be terminated to interfaces, and IP addresses can be assigned to interfaces. You'll need to create a separate circuit in NetBox for each router.
