### ISSUE TITLE
Status indicators in rack view

### ISSUE THREAD

**Issue by WardsParadox** [digitalocean/netbox#1998]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 2.7.12 
* NetBox version: v2.3.1) 

### Description
Currently, when looking at a rack view, you can see different types of devices. This is great. What you can't see at a quick glance is their status. You have to click on the unit and view the status. If one could see the status from either hovering on top of the item in the rack OR via a set of patterns in the coloring, such as a striped pattern in red for failed with the base color of the device role. 
Gray could be offline, red for failed, planned could be blue, stagged could be green, active would just be the base color, etc.

**Comment by jeremystretch** [comment]
I like it, but we need to decide how best to display status? I don't really like the hover option; it would be more useful to see the status of every device at a glance. I also want to keep the current coloring of devices by role. Maybe a toggle button at the top to show/hide a 'status' overlay?

**Comment by Yakelixir** [comment]
Yeah in respect to signal to noise a toogle for this would work in regards to display.

Thoughts on display via toggle...
- box on the side of the device that overlays a color/string/etc (might be cool to be customizable)
- string with color
- symbol w/wo color
- etc

Might work. #designchoices

**Comment by igorrev** [comment]
Yes, it's really necessary feature. We are planning relocation of equipment and need to mark units in rack as reserved for particular devices.

I think, no color. Color is already used for device type and it's good. And no hover, of course. Status information must be visible without user interaction and in print view too.
Symbol is good idea. May be inside device bar in rack or outside device bar on the right of the rack, similar to unit numbers.

**Comment by pm17788** [comment]
Since there is MarkDown support already in the code, perhaps prefix (or suffix) the name of the device in the rack with one of the: 

| Status        | Options           |
| ------------- |:-------------:|
| Failed     | :exclamation: or :sos: |
| Offline     | :zzz: or :white_circle: or :white_square_button: |
| Planned     | :grey_question: |
| Staged     | :white_check_mark: |
| Active     | :heavy_check_mark: |

Regardless of what is chosen, please let's add a legend visible somewhere on the page?

**Comment by ankerstal** [comment]
I really need this as well. My suggestion is some sort of "pattern" since color is already used for type.

**Comment by jeremystretch** [comment]
We might want to shelve this idea and see if #2248 (HTML5 canvas-based rendering) gains traction.

**Comment by jeremystretch** [comment]
After experimenting with SVG-based rendering (#2248), it seems like a _much_ more preferable approach than how we currently render racks. It'll take a bit of work but I hope to fold it into the 2.4 train at some point in the near future. I'm going to close this out since I'm sure whatever we come with will incorporate status illustration in some manner. SVG opens up a lot of possibilities.
