### ISSUE TITLE
Napalm integration

### ISSUE THREAD

**Issue by BlyatFirmeza** [digitalocean/netbox#2016]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.4 
* NetBox version: 2.3.2 

### Description

So i'm trying out NAPALM to see if it can get info on the own server netbox is running (since its linux and napalm has a function with linux).
So i set the ip the same and configure the same username and password i use for SSH connection, but for my suprise in the end it says "No NAPALM driver is configured for this device's platform()."

What can it be, on the photos below you can see i have done everything correctly.
[IMGUR](https://imgur.com/a/3fNyG)
Device: Ubuntu Server 16.04 LTS

Nobody is answering me in this question on netbox-discuss so if you please dont close this i would apreciate it

**Comment by TheGuyDanish** [comment]
I believe the reason you're facing this is because there's no NAPALM driver defined in the platform, [see this screenshot for an example](https://i.imgur.com/N708hwN.png)

However, to my knowledge, there is no support for NAPALM to communicate with Linux directly. So this wouldn't work regardless.
```python
>>> import napalm
>>> napalm.SUPPORTED_DRIVERS
['base', 'eos', 'ios', 'iosxr', 'junos', 'nxos', 'nxos_ssh']
```
And for the record, `base` appears to be a mock driver to help developing new drivers.
