### ISSUE TITLE
Search by interface name

### ISSUE THREAD

**Issue by poofik** [digitalocean/netbox#2043]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.4
* NetBox version:  2.3.3

### Description

If I add a device and call it a "patch-panel" I would like to be able to search the interfaces by names. Example 1B-0101. Currently searching interface by name does not find anything.

**Comment by jeremystretch** [comment]
As interface names are generally platform-dependent, it doesn't make sense that you'd want to search for e.g. "ge-0/0/0" and get a bunch of Juniper switches, or "eth0" and get a bunch of Linux servers. This request seems to be born out of an attempt to represent patch panels, which NetBox does not yet support (see #20). If you really need to, you can filter interfaces by name in the REST API like this: `/api/dcim/interfaces/?name=foo`

**Comment by poofik** [comment]
I know it was rejected feature, but if I was to branch and implement the feature myself any pointers? Files and functions that need to be modified? API works exactly as I wanted but need the GUI.

**Comment by netsiphon** [comment]
I already implemented interface search and that part was rejected as part of PR #1465 with somewhat similar reasoning to your request. I was actually looking to use the description field generically as a label and import/export them from current documentation.  Don't recall if he rejected the idea of descriptions in general but he definitely could tell that I was trying to implement some physical tracking and doesn't want to support that outside an official feature. I'd be willing to work on #20 since it aligns with my interests but I'm not sure what kind of consensus is required for that to move forward.

There were changes Jeremy requested that I didn't have a chance to correct but you can check against that PR or pull netsiphon/netbox to see if that is what you are looking for (older version of netbox).
