### ISSUE TITLE
Request search for MAC address

### ISSUE THREAD

**Issue by emarton77** [digitalocean/netbox#2054]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.2 
* NetBox version: 2.3.2 

### Description
Would be nice to have the ability to search for MAC addresses in any format from the UI. Would help track down interfaces of servers and/or VM's by MAC rather then by IP.

**Comment by Keyhaku** [comment]
Hello,

It seems it's already implemented, see [1379](https://github.com/digitalocean/netbox/issues/1379)

You can globally search for MAC addresses (in the global search input field), but I don't know why it doesn't seems to work.

Or you can use the dedicated filter in dcim -> Devices view, there is an input field on the bottom of the search box to the right of that page.

@jeremystretch It seems this dedicated filter doesn't exist for Virtual Machine, is it desired ?

**Comment by jeremystretch** [comment]
@emarton77 There's a "MAC address" field in the search form to the right-hand side of the devices list.

@Keyhaku We can add one for virtual machines, but please open a new ticket specifically for that.

**Comment by jkldgoefgkljefogeg** [comment]
It would be nice for global search bar (top right, next to username) to include MAC search.

**Comment by jsuter1** [comment]
Global search for MAC address works for me in v2.5.8. However, the global search only supports the `AABBCCDDEEFF` MAC address format. The MAC address search field on /dcim/devices allows both the `AA:BB:CC:DD:EE:FF` and the `AABBCCDDEEFF` formats. 

@jeremystretch Is it possible for the global search to support both formats?

Also referencing #1379 since I found that first when looking for the ability to search by MAC.

**Comment by eronlloyd** [comment]
Bumping for global MAC search in multiple common notations. I’ve seen them as
* MM:MM:MM:SS:SS:SS
* MM-MM-MM-SS-SS-SS
* MMM.MMM.SSS.SSS
