### ISSUE TITLE
Add "Local Only" Option for Services

### ISSUE THREAD

**Issue by vandlol** [digitalocean/netbox#2114]
[ x] Feature request 
[ ] Bug report      
[ ] Documentation   

I would love to have a Local Only bool for Device Services.
I have a lot of Servers with localhost only services which need to be registered.
But to achieve this i'd have to assign a localhost interface + localhost ips to each and every server - is this the intended way?
This would make a great addition to "All IPs", "Specific IPs Only"

**Comment by jeremystretch** [comment]
What is your motivation behind recording services which are only locally-accessible in NetBox?

**Comment by pm17788** [comment]
@jeremystretch: Mine is that it give my monitoring system information about what sockets should be open on the host when I run something like `netstat -ntap`

**Comment by vandlol** [comment]
I try to use netbox as a transparent documentation.
I have apache running locally on a lot of maschines and other services redirecting to this locally running instance.

**Comment by jeremystretch** [comment]
If you need to model services which are only locally accessible, the canonical approach would be to create `lo0` or its analog, assign it `127.0.0.1/8` and/or `::1/128`, and assign the local services to those IPs. Granted, this is more work, but that's how the services operate in reality, so that's how we'd model them in NetBox.
