### ISSUE TITLE
Ability to selectively hide custom fields from the web UI

### ISSUE THREAD

**Issue by pm17788** [digitalocean/netbox#2132]
### Issue type
[x] Feature request

### Environment
* Python version:  3.5.4 
* NetBox version: 2.3.2

### Feature Request:
As a thought, what about having a flag on a custom field which would hide it from the UI view? Still present via API, though.
I find that I have users who just want the WebUI, and for them, an overabundance of custom fields is confusing (especially those which are packed for machine-parseability). The API users I basically don't care about in that if they're using the API, it's on them to filter stuff they don't want to see .

**Comment by pm17788** [comment]
A split-off from #2120

**Comment by a31amit** [comment]
@jeremystretch  https://github.com/digitalocean/netbox/issues/2383 seems a little different where the user can selectively display them on device page and see everything in inventory page. 

If you consider that, this can be included altogether.

**Comment by jeremystretch** [comment]
I had previously marked this as accepted, but after giving it more thought I don't think it's a good fit. We try to maintain parity between the web UI and the API, and this would intentionally diverge from that. It's also worth pointing out that config contexts have been implemented since this was proposed, which may provide a better place to store data that isn't necessarily interesting to users.
