### ISSUE TITLE
Prefix length error while adding child prefixes 

### ISSUE THREAD

**Issue by JSystem1** [digitalocean/netbox#2181]
### Issue type
[ ] Feature request 
[X ] Bug report      
[ ] Documentation   

### Environment
* Python version: 2.7 
* NetBox version: 2.3.2  

When trying to POST a child prefix to the following endpoint `api/ipam/prefixes/(parent-prefix)/available-prefixes`

You get the following error complaining about prefix length:
`<pre><strong>&lt;type &#39;exceptions.KeyError&#39;&gt;</strong><br />
u&#39;prefix_length&#39;</pre>`

The following is the json I am passing 

`{
  "prefix": "ip/29",
  "status": {
    "value": 1,
    "label": "Active"
  }
}`

**Comment by jeremystretch** [comment]
The point of the `/available-prefixes/` endpoint is that it will automatically provision the next available prefix: You just have to specify the size (`prefix_length`) in the request. If you want to provision a specific prefix, use the `/api/ipam/prefixes/` endpoint. (Also, you only need `"status": 1` for the status field.)

That said, the API should return a validation error rather than an exception.
