### ISSUE TITLE
I am unable to get the association between VM and IP address to work

### ISSUE THREAD

**Issue by lmlavinjr1** [digitalocean/netbox#2186]
I took the steps you managed in the documentation for a virtual machine... was never offered a list of IP addresses..
I have filled the IP tables, the virtual machine tables.. even assigned Clusters to the virtual machines.. but cannot get the IP addresses to tie to the virtual machines... This is ovm manager.. DO I need to create OVS physical servers as well before I create the VMs?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by lmlavinjr1** [comment]
### Issue type
[ ] Feature request 
[ ] Bug report      
[x] Documentation   


### Environment
* Python version:  2.7.5
* NetBox version:  2.3.2


### Description

**Comment by jeremystretch** [comment]
This doesn't sound like a feature request or bug report. Please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you need assistance.
