### ISSUE TITLE
Site status is not exposed via /api/dcim/_choices

### ISSUE THREAD

**Issue by ebusto** [digitalocean/netbox#2191]
Issue type
[ ] Feature request 
[X] Bug report 
[ ] Documentation

NetBox version: v2.3.4
Description
The possible choices for the site status are not exposed via /api/dcim/_choices.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by ebusto** [comment]
Similarly, interface mode is not exposed.
