### ISSUE TITLE
User profile images + additional information

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#220]
Would be nice to have this, or, have some predefined ones available.

When in doubt, gravatar is always works.

I know it seems silly but in the realm of multi-tenancy (#16) it might apply to have a company logo for a profile, etc

Would be nice to have a phone number in there too or support for #158

**Comment by jeremystretch** [comment]
Where would user profile images be displayed?

**Comment by bellwood** [comment]
I think to honestly answer that we'd need to see the initial roll out of #16 and what it introduces into the UI. If the only place it might appear would be in the profile then it's usefulness is limited.

If "Recent Activity" is going to be logging actions of other multi-tenant users, it might be nice to identify these actions by a profile image to the left (or at least the profile name, etc)

Don't have a great answer =)

**Comment by jeremystretch** [comment]
I don't see significant value in supporting user avatars since the concept of a user in NetBox is mostly just for authentication and authorization purposes. We can possibly extend the tenant model to include additional info, but that would be a separate issue (maybe covered by #503). I'm going to close this out due to lack of activity.
