### ISSUE TITLE
Ability to rename interfaces under types/devices

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#224]
Rather than delete, recreate and re-associate connections it would be nice to be able to rename interfaces (e.g fa-0/1 <---> fa0/1 <---> FastEthernet0/1)

I already know there will be much discussion internally about the format and having basically loaded all my data up going back through it again for renaming would be tedius

**Comment by jeremystretch** [comment]
Interfaces can be edited and renamed individually from the device view, at `/dcim/interfaces/{pk}/edit/`. They can also be renamed in bulk using the yet-to-be-documented shell. (For device types, it's easiest to simply delete and recreate interface templates.)

**Comment by jeremystretch** [comment]
Bulk editing of interfaces is probably best done through the shell. Going to close this issue and hopefully publish some documentation around the shell soon.

In practice, this should be a very rare occurrence, since interfaces should be named however they are referred to on the device. For example, Cisco IOS would call an interface "FastEthernet0/1"; although "fa0/1" can be used as a shortcut on the CLI, the interface is never referred to in this manner.
