### ISSUE TITLE
Container for loopbacks shows 0% utilisation

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#2263]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.5

### Description

* Create prefix 192.0.2.240/29 of type "container"
* Create IP address 192.0.2.240/32, role "loopback"
* Create IP address 192.0.2.241/32, role "loopback"

I was expecting to see the container as 25% used.  But it shows 0% used.

I infer from this: container prefixes are counting only contained prefixes towards utilisation, and not individual IP addresses which are contained directly by the container?

**Comment by jeremystretch** [comment]
> I infer from this: container prefixes are counting only contained prefixes towards utilisation, and not individual IP addresses which are contained directly by the container?

This is correct. Changing the prefix to "active" (or anything other than "container") will [calculate utilization](https://github.com/digitalocean/netbox/blob/develop/netbox/ipam/models.py#L359) based on IP addresses rather than child prefixes. This approach was chosen because either approach to determining utilization may be desired depending on the context.
