### ISSUE TITLE
Address / Prefix overlapping check button

### ISSUE THREAD

**Issue by fallenfuzz** [digitalocean/netbox#2293]
### Proposed Functionality

Button to check overlapping IPs upon prefixes during prefix / address creation.

### Use Case

You have bunch of prefixes and creating overlapping one my mistake can be identified quicker with a button, instead of seeng that it is duplicate only once created.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. It looks like your feature request is missing some information. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md), please ensure that you have provided all of the following:

* A detailed description of the proposed functionality
* A use case for the feature; who would use it and what value it would add to NetBox
* A rough description of changes necessary to the database schema (if applicable)
* Any third-party libraries or other resources which would be involved

Please update the issue so that it meets all of  these requirements. If no response is received within a week, this issue will be closed. Thanks!

**Comment by fallenfuzz** [comment]
Hi @jeremystretch ,

No idea about the bellow, I'm not a developer, just posted idea that would help imho

A rough description of changes necessary to the database schema (if applicable)
Any third-party libraries or other resources which would be involved

Bellow already there, I'll add a picture that might clarify 
A detailed description of the proposed functionality
A use case for the feature; who would use it and what value it would add to NetBox

![1](https://user-images.githubusercontent.com/13089287/43589114-b60621da-9676-11e8-9f40-bac8a53c7c97.png)

Hope that helps.

Thanks for your hart work and great tool!

**Comment by jeremystretch** [comment]
This would be covered by #418. Please add your comments there if you'd prefer a button.
