### ISSUE TITLE
Ability to reference a connection between devices via URL

### ISSUE THREAD

**Issue by dgomes87** [digitalocean/netbox#2298]
edited message:
**Environment**: Ubuntu 16.04
**Python version**:  Python 2.7.12
**NetBox version**: v2.3.5

**Proposed Functionality**
Adding the ability to click a button or URL next to each established or planned connection on a device. This button or URL opens a page that lists point A and B of the connection, similar to the page shown when originally creating a connection. This URL can then be used to link directly to a connection rather than having to reference both devices individually when opening tickets, or creating/referencing documentation.

**Use Case**
Referencing very easily via email/tickets or physical QR codes a direct link (URL in browser) to a connection between 2 devices (power and networking).
As opposed to having to look up the device and scroll through the ports, and link to both devices individually.

**Database Changes**
Not a developer, so do not know. The data is already there so I assume none.

**External Dependencies**
Not a developer but I assume none.

**original message**:
Is there any way to reference a connection between devices via a URL? For example when you create a new connection it shows you the page with Side A and Side B. However once the connection is created I can't seem to find a way to get back to this page. I want to be able to print QR codes to stick on my cables that will pop up this URL showing Side A and Side B.

If this doesn't exist can this be a feature request?

Thanks,

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/tree/develop/.github/ISSUE_TEMPLATE). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the appropriate template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by dgomes87** [comment]
@jeremystretch I've updated the message, thanks.

**Comment by jeremystretch** [comment]
This doesn't seem like a reasonable view to implement given the current model: All the information it would provide is already available elsewhere (i.e. on the device view). I'm sure we'll come up with something covering this as part of #20 in v2.5 anyway, once NetBox has been extended to model cable paths.
