### ISSUE TITLE
API call to Interfaces seems slow

### ISSUE THREAD

**Issue by mw-0** [digitalocean/netbox#2352]
### Environment
* Python version:  3.4.8
* NetBox version:  2.3.4

### Steps to Reproduce

Call the api endpoint
time curl http://netbox/api/dcim/interfaces/?limit=100

### Expected Behavior

Data returned is ok but i would expect it to be far quicker based on data size.

### Observed Behavior
When checking times for the API i can see the calls to api/dcim/interfaces/ seem slow.

When i call /api/dcim/interfaces/?limit=100 it takes 4.5sec

Comparing this to /api/dcim/devices/?limit=100 it takes 1.3s

If i compare the amount of data returned devices shows over double the content for the call as well.  I have seen a ticket that sped up the devices call closed and was wondering if interfaces could also be helped.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/tree/develop/.github/ISSUE_TEMPLATE). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the appropriate template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by jeremystretch** [comment]
> i would expect it to be far quicker

This isn't an actionable statement. Like every application, NetBox's performance is dependent largely upon the environment in which is runs. If you can identify specific opportunities for performance improvement I'll be happy to look into them.
