### ISSUE TITLE
Enable filtering devices by assigned rack face

### ISSUE THREAD

**Issue by ebusto** [digitalocean/netbox#2357]
### Environment
* Python version:  3.5.4
* NetBox version:  2.4.3

### Proposed Functionality
Add the ability to search for devices based on rack position and face.

### Use Case
It is handy to be able to search for devices in a specific part of a rack, which the combination of position and face should accomplish. I believe this is a trivial change to `netbox/dcim/filters.py`.

### Database Changes
None.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
FYI `position` is already an available filter.

**Comment by jeremystretch** [comment]
We may have painted ourselves into a corner with this one. The face is stored as a nullable integer value in the database, with `0` meaning front and `1` meaning rear (and `null` meaning neither). However, we're using `0` as a special value to represent null for filters, so querying `?face=0` will return only devices with no face assignment.

We have a few options:

1. Change the `face` field to use different values (e.g. "front" and "rear") instead of 0 and 1. This requires a database migration.
2. Use different values for the filter. I don't like this because it's inconsistent. For example, querying `?face=front` will return a device which has `face=0`.
3. Change the value used to represent null. While an argument can be made for this option, it's likely too disruptive to be justified.

**Comment by jeremystretch** [comment]
Marking this as blocked by #2632

**Comment by tb-killa** [comment]
Hi I would ask if there is something new?
#2632 is closed and I like your idea of:

Change the face field to use different values (e.g. "front" and "rear") instead of 0 and 1.

**Comment by candlerb** [comment]
@tb-killa: #2632 was closed because it was implemented in 2.5.0.

This opens the route to implementing a filter for `face=0`, `face=1` and `face=null`, but I don't think that's been implemented yet (hence this ticket remains open)
