### ISSUE TITLE
Add Expand button to 'Child Prefixes' tab

### ISSUE THREAD

**Issue by cjreyn** [digitalocean/netbox#2364]
Currently the 'expand' button is only on the main prefixes landing page. It would be great if it was present on the Child Prefixes page, so children of the Child prefixes can be expanded.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/tree/develop/.github/ISSUE_TEMPLATE). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the appropriate template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by cjreyn** [comment]
### Environment
* Python version:  3.4.3
* NetBox version:  2.4.1


### Proposed Functionality
Currently the 'expand' button is only on the main prefixes landing page. It would be great if it was present on the Child Prefixes page, so children of the Child prefixes can be expanded.


### Use Case
Daily view of prefix information


### Database Changes



### External Dependencies

**Comment by snowie-swe** [comment]
+1 on this, very helpfull when you have multiple containers within other containers.

**Comment by jeremystretch** [comment]
I'm going to close this ticket in favor of #2598 opened by @snowie-swe which includes a bit more detail.
