### ISSUE TITLE
Can Aggregates Take into account IP Addresses not just Prefixes?

### ISSUE THREAD

**Issue by frasercarter** [digitalocean/netbox#237]
As title.

I'd like to be able to see available IP addresses within some of my IP aggregates, for example if I want to monitor IP availability for some Public Subnets, I dont want to have to create /32 prefix's

Could there be an option within a prefix to select whether it reports by Prefix or IP utilization as obviously we cant report both.

**Comment by jeremystretch** [comment]
Reporting on individual IPs used is actually a lot simpler than accounting for child prefixes, since it's just a count of all IP addresses within the aggregate prefix as a fraction of the total available IPs. For example, if an aggregate 192.168.0.0/16 has 4827 IPs defined, its utilization is 4827/65536 (~7%).

It may be reasonable to display both prefix and IP utilization in the aggregate table, depending on how much room we need for the description.

**Comment by Gelob** [comment]
Maybe a dupe or similar to https://github.com/digitalocean/netbox/issues/40 ?

**Comment by candlerb** [comment]
> Reporting on individual IPs used is actually a lot simpler than accounting for child prefixes

Not much use for IPv6 though! I suggest for that case, the figure of interest is the number of /64's touched.

> if an aggregate 192.168.0.0/16 has 4827 IPs defined, its utilization is 4827/65536 (~7%)

Yes this is possibly an interesting figure, but may be misleading. It can hide that you have some prefixes at or close to 100% utilisation, and no way to grow them without serious renumbering.

I think the real issue is that Netbox only reports utilisation at the level of *Aggregate*, not at the *Prefix* level.  If you could see utilisation of each prefix separately, that would go a long way I think.

Within a prefix:

1. If it contains only IP addresses, then you can report the utilisation as (IPs defined / total space)
2. If it contains prefixes, then you can report the utilisation as (child prefix space / total space)
3. If it contains both, then you count (child prefix space) + (IPs directly contained but not within child prefixes) - although that's admittedly an odd situation

And maybe (1) and (2) should be different colours.

**Comment by jeremystretch** [comment]
There doesn't seem to have been much interest in this so I'm closing it out.
