### ISSUE TITLE
VRF as a per-node database schema 

### ISSUE THREAD

**Issue by adamv0025** [digitalocean/netbox#2372]
Looks like netbox is looking at the VRF thing from a wrong angle unfortunately. 
It seem to treat it as a network-wide thing, where in fact VRF is very much a per-node thing.

All the parameters you can define for a VRF are per-node specific::

**Name:** vrfa-a-on-rtr-a & vrf-a-on-rtrb (we just tend to use common names for clarity)
**RD:**  vrfa-a-on-rtr-a & vrf-a-on-rtrb (once again just an operators choice on how many unique sets of routes they need, and what RD format they’ll use for that (Type-1/2/3 RDs)
**Export RT/policy:** (again just an operator’s choice to make these unique or common across nodes and for a particular set of prefixes –as defined by the policy)
**Import RT/policy:** (again just an operator’s choice to make these unique or common across nodes and for a particular set of prefixes –as defined by the policy)
**Interfaces:** list of interfaces associated with a vrf which is very different on each node 

And really don’t understand what’s this thing with assigning prefixes to VRFs
-where do I configure that on a router?
-or is it supposed to be replica of VRFs routing table? -good luck with keeping internet vrf records up to date then ;) 
-I’d assign a prefix to customer or an interface, but never to a VRF
-the only place I could see related to a prefix in VRF realm is to record the import/export policy in the database  –again unique per node (where a specific prefix gets a specific RT, or route is accepted only if both RT as well as prefix matches)

This is related to: #1215

adam

**Comment by lampwins** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the appropriate template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

Aditioonally, please take a look at the docs for the [VRF model](https://netbox.readthedocs.io/en/latest/core-functionality/ipam/#virtual-routing-and-forwarding-vrf). This will give you an idea of NetBox's intentions when modeling a VRF.

**Comment by jeremystretch** [comment]
It sounds like NetBox isn't the right solution for you.
