### ISSUE TITLE
Admin section issue

### ISSUE THREAD

**Issue by sergeyrusak** [digitalocean/netbox#2395]
Hi!

### Environment
* Python version:  Python 3.6.5
* NetBox version:  2.4.4 (moved from different server from version: 2.3.1)

### Steps to Reproduce
The page https://netbox.domain.local/admin/ shows error:

**<class 'django.template.exceptions.TemplateDoesNotExist'>
django_rq/index.html**

### Expected Behavior
Get control panel

### Observed Behavior
-

Thank you.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by tobiasge** [comment]
Hello,

@jeremystretch 
we are also facing this issue. The problem is with having django_rq installed but webhooks disabled. This happens when using the Docker container from Nine.ch. In this container the `django_rq` is always installed, but you can still disable the webhooks backend. 

So when webhooks are disabled in the `settings.py` you have these lines (from 161):
```
# Only load django-rq if the webhook backend is enabled
if WEBHOOKS_ENABLED:
    INSTALLED_APPS.append('django_rq')
```

And in the `netbox/admin.py` you have this (from line 25):
```
# Modify the template to include an RQ link if django_rq is installed (see RQ_SHOW_ADMIN_LINK)
try:
    import django_rq
    admin_site.index_template = 'django_rq/index.html'
except ImportError:
    pass
```

I think a good fix for this would be to check in `admin.py` if the setting WEBHOOKS_ENABLED is true.

Kind regards
Tobias

**Comment by DanSheps** [comment]
Upgrade to 2.4.7
