### ISSUE TITLE
Please reopen Bug #2395

### ISSUE THREAD

**Issue by Keyhaku** [digitalocean/netbox#2509]
The admin section is not reachable since netbox 2.4.4.

The bug is legit, and the PR provided mitigate the problem.

**Comment by traveler3468** [comment]
Im able to get to the admin section and Im on version 2.4.5

**Comment by jeremystretch** [comment]
**Do not** open a new issue to ask about an existing issue. #2395 was closed because it did not meet the standard of quality for new issues. If you want to re-raise the issue, submit a **new** issue with the issue template fully completed, keeping in mind that a suspected bug must be reproducible in the official code base; we do not address bugs which affect only third-party releases.
