### ISSUE TITLE
Ability to sort and filter IP Address page

### ISSUE THREAD

**Issue by rekkoner** [digitalocean/netbox#253]
Would be helpful to be able to filter down based on certain filters or criteria, such as:

filter to 10.10.10.* only

Unused or used IPs only, possibly in combination with previous filter. (See #252)

This pertains mainly to the IP Address main screen (from the 'IP Space' menu), but would apply on other similar screens, such as from the IP Addresses tab of the Prefixes screen.

**Comment by bellwood** [comment]
The best way to potentially do this would be to:

-populate the filter with the list of current aggregates under which the filtered prefix resides (/ipam/prefixes/)

-populate the filter with the list of current prefixes under which the filtered address resides (/ipam/ip-addresses/)

...mainly due to the aggregate -> prefix -> address workflow.

Would this be acceptable?

**Comment by rekkoner** [comment]
Yeah, I think that would work. In our case, for example, we use two wildly different 10. IP schemes for primary and DR DCs. I think that's a good way to easily filter and drill down based on such a thing
