### ISSUE TITLE
2.5b1 Migration of RackRole Failed

### ISSUE THREAD

**Issue by mmahacek** [digitalocean/netbox#2575]
### Environment
* Python version:  3.6
* NetBox version:  2.5 beta 1

### Steps to Reproduce
Access /dcim/rack-roles page

### Expected Behavior
The Rack Roles page should load.  I checked my 2.4.7 server, and the page loads properly.  On my test servers (which was a VM clone of production), there is an error when accessing the page.

### Observed Behavior
```
<class 'ValueError'>

table data is of type <class 'dcim.models.RackRole'> but <class 'dcim.models.RackGroup'> is specified in Table.Meta.model
```

**Comment by jeremystretch** [comment]
Wow. This has been wrong for [over two years](https://github.com/digitalocean/netbox/commit/ed0344916424ff0f4c8b756c900e16864eb7e6e9#diff-516bb36270a80a0461e7b9ce20f91febR117). It's just never been a problem since the RackRole and RackGroup models are so similar. Looks like a validation check was added in a more recent release of django-tables2.
