### ISSUE TITLE
Feature Request: Reject Device removal if interface connection exists

### ISSUE THREAD

**Issue by berahtlv** [digitalocean/netbox#2595]
### Environment
* Python version:  3.5 - onwards
* NetBox version:  2.4.7 - onwards

### Proposed Functionality
Reject removal of Device if interface connection exists.

### Use Case
As interface connections of not discoverable devices are manually entered, mistaken deletion of device can lead to loss of valuable information.

### Database Changes
None. 
As I understand, some back-end method that checks connection existence before deletion will be needed.

### External Dependencies
No additional.

**Comment by DanSheps** [comment]
Personally, I don't see a use for this.  You get promoted a "are you sure" already looking at a stacked cat 9300 for example, you could have around 500 connections that need to be disconnected.

I don't believe there is a bulk disconnect option, which would also need to be added in order to sanely support this.

Just my view though

**Comment by jeremystretch** [comment]
I'd rather not force users to manually disconnect every connection to a device before they remove it. I think the current implementation of the warning page is sufficient. Ultimately the user is still responsible for paying attention to what they're doing.
