### ISSUE TITLE
Add FibreChannel SFP28 (32GFC) interface support

### ISSUE THREAD

**Issue by swerveshot** [digitalocean/netbox#2597]
### Environment
* Python version:  3.6.7
* NetBox version:  v2.5-beta1

### Proposed Functionality
Just like issue #2561 I spotted an interface type that is not available in Netbox yet: 32G Fibre Channel (32GFC) SFP28. It would be really nice if you could include it. :heart:

https://www.finisar.com/optical-transceivers/ftlf8532p4bcv

**Comment by swerveshot** [comment]
Hey @jeremystretch!

Thanks for adding the 32GFC support. From what I can tell it's not that hard to add any additional interface types. If I wanted to add even more interface types could I simply fork the project (development tree) and then add them to the 0062_interface_mtu.py and constants.py files?

I was recently made aware by a colleague that there is also a 4x32GFC QSFP28 interface type available (Brocade part number [XBR-000275).](https://docs.broadcom.com/docs/12379902) Would I name it as IFACE_FF_4X32GFC_QSFP28?

**Comment by DanSheps** [comment]
@swerveshot You would:

* add them to the constants.py
* python3 <pathtonetbox>/netbox/manage.py makemigrations

As a best practice, I would do the following:

* Fork the repository
* git clone https://github.com/<you>/netbox
* git checkout develop
* git checkout -B <issue#>-description
* make changes
* python3 <pathtonetbox>/netbox/manage.py makemigrations
* git add .
* git commit -m"Fixes #<issue#> - Proper description"
   * You can go further if you want and list out everything that was changed in a more detailed commit message
* git push origin <issue#>-description
* Open a pull request

This is just what I would do, you can really do it however you want, but I would say work in adifferent branch then develop, otherwise you end up polluting the pull request with extra fluff as well.

**Comment by DanSheps** [comment]
Yes, you would need a fully functional install of netbox, including PostgreSQL

**Comment by swerveshot** [comment]
Okay @DanSheps now it gets interesting. Do you have any thoughts on how to get you own fork up-and-running really fast? I tried the [Vagrant](https://github.com/ryanmerolle/netbox-vagrant) route and that works. All you need to do is change the URL of the repo. But it would be really awesome if I could use [Docker Playground](https://play-with-docker.com) and avoid having to host my own Netbox fork in a VM. But unfortunately I have no idea how to accomplish this.
