### ISSUE TITLE
Add a Many:Many connection device

### ISSUE THREAD

**Issue by millijuna** [digitalocean/netbox#2695]
### Environment
* Python version:  3.6.5
* NetBox version:  2.5.1

### Proposed Functionality

It would be very helpful for capturing my campus network configuration to be able to document my Many:Many splice enclosures. Conceptually, the idea would be akin to connecting rear ports to each other.

Related: when dealing with rear ports, it would be great to have a "Fusion Splice" connector type.

### Use Case

In my campus network, I have a significant quantity of OSP (OutSide Plant) cable that comes into our main administration building. Due to fire regulations (OSP cable is only permitted 50' inside a structure), and due to mechanical constraints, that OSP cable goes into a splice enclosure in the basement. 

Inside the enclosure is a series of splicing cassettes that each take two OSP cables (6 SMF strands) and splice them onto a riser cable that has 12 strands.

Another use case for this would be other situations where you're transitioning from one cable to another, with a change in designation/color/other property, or peeling a fiber pair off of a trunk cable.

### Database Changes

Could possibly need some relaxation of constraints to permit rear ports to be connected to each other.

**Comment by jeremystretch** [comment]
Unfortunately the data model we've implemented for cabling doesn't support directly splicing one cable to another. It's important to remember that the data model we decided on during the v2.5 beta period was chosen because it strikes a reasonable balance between flexibility, performance, and maintainability.

In your case, I'd probably create a device to represent the splicing enclosure, with the cables terminated as rear ports and "patched" together via front ports. You should be able to model this with a single device. Alternatively, you could model one or both cables continuing for the entire span, with the understanding that it doesn't fully reflect reality.
