### ISSUE TITLE
Add port type "E2000"

### ISSUE THREAD

**Issue by mikek-70** [digitalocean/netbox#2708]
Please add "E2000" as a fiber optic port type in /dcim/constants.py

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by DanSheps** [comment]
@mikek-70 This is a LSH connector

**Comment by mikek-70** [comment]
@DanSheps I've learned that in the meantime... thanks! We always call it E2000, have never used the term LSH before, but for documentation in Netbox, it is of course the correct and standardized term.
