### ISSUE TITLE
Allocating ip address from a group of predefined prefix

### ISSUE THREAD

**Issue by tongorz** [digitalocean/netbox#2720]
Use Case: 
Useful for interconnect ip address allocation In Data Center
For Example:
Having A group of aggregates : 
- 10.0.1.0/24 
- 10.0.2.0/24 
- 10.0.3.0/24
- 10.0.4.0/24

Per interconnect ip address allocation action giving a group of /30 prefixs for a pair of interconnected network devices :
- 10.0.1.4n/30
- 10.0.2.4n/30
- 10.0.3.4n/30
- 10.0.4.4n/30
- where n = [0,64)

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
