### ISSUE TITLE
Bulk Update MAC Address

### ISSUE THREAD

**Issue by thefathacker** [digitalocean/netbox#2733]
### Environment
* Python version: 3.6.7
* NetBox version: 2.5.2

### Proposed Functionality
Bulk Update MAC Addresses for Device Interfaces

### Use Case
Allows Quicker MAC Address Assignment when creating Switch Devices

### Database Changes
Not Required Functionality/Data Already Exists

### External Dependencies
Not Required Functionality/Data Already Exists

**Comment by DanSheps** [comment]
I think a better way to do it, on a purely graphical level, is to have a "base" mac and the increment accordingly.

**Comment by DanSheps** [comment]
Generally a switch will have a base mac address, which all other interfaces (virtual, physical, etc) are derived from.

Lets say your base mac on a cisco switch is 0001.aade.3200

Eth1/0/1 would be 0001.aade.3200
Eth1/0/2 would be 0001.aade.3201

and so on.

I am almost 99% of the cases, you won't be a in a situation where each interface will have the exact same mac address.  Only pseudo interfaces (subinterfaces, etc) will share a mac address.

**Comment by jeremystretch** [comment]
The MAC address field was omitted from the bulk update feature since MAC addresses are typically unique. Do you have a use case where you need to assign the same MAC address to multiple interfaces?

> I think a better way to do it, on a purely graphical level, is to have a "base" mac and the increment accordingly.

While I agree with the use case, this would be pushing the limited logic of the bulk update function a bit too far. Any programmatic changes are better handled via the API.

**Comment by jeremystretch** [comment]
There's not really any harm in enabling this functionality, and there's a use case for at least being able to nullify existing MAC addresses.
