### ISSUE TITLE
netbox-directory active

### ISSUE THREAD

**Issue by jorgepg92** [digitalocean/netbox#2749]
Hello
is it possible that netbox can store the ip addresses delivered by an active directory by dhcp? that is, if there is a change in some this is automatically seen in netbox?

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
