### ISSUE TITLE
LAG visibility between Parent and Child devices. 

### ISSUE THREAD

**Issue by marcinkorzycki** [digitalocean/netbox#2752]
### Environment
* Python version:  3.5.3
* NetBox version:  2.5.2

    I would like to have visibility of LAG created in Parent Core Switch on Child Core Linecard added via Device Bay. I have Dell C9010 which is an Network Chassis with modules. Every Port-Channel is visible on whole core switch, not only on specific module.

### Steps to Reproduce
![screenshot_1](https://user-images.githubusercontent.com/24276423/50728000-d6654780-1123-11e9-95b1-5ea7f055f2f9.png)
![screenshot_2](https://user-images.githubusercontent.com/24276423/50728002-d8c7a180-1123-11e9-9022-2968e82c3348.png)
![screenshot_3](https://user-images.githubusercontent.com/24276423/50728003-d9f8ce80-1123-11e9-916d-83f582993e99.png)

### Expected Behavior
Enable LAG created in Parent Device on Child Device or additional checkbox while creating LAG interface in parent device that it can be visible on child device.

### Observed Behavior
Can't choose LAG created in Parent Device on Child Device. It is visible only in Parent Device.

**Comment by lampwins** [comment]
This is a misuse of Parent/Child devices. This concept in NetBox is meant for chassis-based devices in which the chassis provides nothing more than power to a child in a device bay. Think blade servers, not networking line cards. When the line card is "dumb" meaning that outside of the chassis, it serves no purpose at all, it should not be modeled as a child device, because it is not a device at all; it is just a line card that provides interfaces.

Instead, create your chassis as the normal device and add all the line card interfaces directly to it. You can then add the line cards as inventory items on the chassis if you so choose.
