### ISSUE TITLE
Split and create subnets according to the mask specified

### ISSUE THREAD

**Issue by clifforddsouza** [digitalocean/netbox#2774]
### Environment
* Python version:  
* NetBox version:  
![split subnet](https://user-images.githubusercontent.com/29113854/51030970-182d3c80-15c1-11e9-99fa-8996dc9b575b.JPG)

### Proposed Functionality
Hi
Would be super helpful if a automatic split or resize subnet feature can be created, currently we are using PHPIPAM and my network team says we can giveup PHPIPAM if we can get this done in netbox, for me that would work as well as that would mean 1 less system to handle. 

Regards

Clifford Dsouza

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
