### ISSUE TITLE
Unable to filter Sites by multiple Regions

### ISSUE THREAD

**Issue by jbakklund** [digitalocean/netbox#2781]
### Environment
* Python version:  3.5.3
* NetBox version:  2.5.3

### Steps to Reproduce
1. Make sure that you have entered Sites for multiple regions like for example Africa, America, Asia, Australia, and Europe.
2. In the Sites view Search/Filet box, select multiple (two or more) Regions and click Apply.

### Expected Behavior
You would expect NetBox to be able to show all Sites in the selected Regions, in the same way as if you select to filter Sites by e.g. multiple Tenants.

### Observed Behavior
The resulting list shows only Sites for the alphabetically last one of the Regions selected in the filter box.

**Comment by DanSheps** [comment]
I have been looking into this a bit.  Due to the way the current method works to filter, it returns no query objects if a region is invalid.

This is due to the way TreeNodeChoiceField (the form object) cleans the data, if it encounters an invalid region, it just short-circuits and returns the full queryset for filtering.  This is the way it works with device filter or even site filter with the status field (not a TreeNodeChoiceField but a MultipleChoice field).

I am thinking we want to be consistent with the behaviour and the best bet would be to extend ModelMultipleChoiceFilter to "TreeNodeMultipleChoiceFilter" and override filter() to perform a get_descendants query before going to the parent.

This would allow handling of things like NestedRackGroups or anything else that uses the MPTT model.

Thoughts?
