### ISSUE TITLE
Organization->Tags menu returns error

### ISSUE THREAD

**Issue by vooray** [digitalocean/netbox#2853]
Hi!

After upgrading netbox from version 2.5.2 to 2.5.5 menu Tags from Organization->Tags  terurns server error page:

Server Error
There was a problem with your request. Please contact an administrator.
The complete exception is provided below:
<class 'django.urls.exceptions.NoReverseMatch'>
Reverse for 'tag' with arguments '('',)' not found. 1 pattern(s) tried: ['extras/tags/(?P<slug>[\\w-]+)/$']

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
