### ISSUE TITLE
add distinction between OS1 and OS2 for singlemode fiber in constants.py

### ISSUE THREAD

**Issue by fischa** [digitalocean/netbox#2873]
I was stumbling across the distinctions between the different kind of multimode fiber when "connecting" a cable between interfaces. But there was no distinction between OS1 and OS2 for singlemode fiber - just "Singlemode Fiber" is available right now.

Feedback I got in slack was positive that this was missing (not just for me). Shall I create a PR?

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
