### ISSUE TITLE
Device table showing role colours wrong

### ISSUE THREAD

**Issue by stuntguy3000** [digitalocean/netbox#2877]
### Environment
* Python version: 2.7.5
* NetBox version: 2.5.5

### Steps to Reproduce
1. Add a device role and set the colour to text which needs to be rendered as black (e.g. **Yellow**)
2. Navigate to the devices overview page
3. Observe the device with the associated role's label is not rendering the text as black (like in the device role table)

### Expected Behavior
I expect the text labels in the device role overview to render the same in the device table.

### Observed Behavior
In the devices view, the roles are showing text colours inconsistently with the device role editor page.

Example here is the yellow Other Host label, text is wrong and unreadable on the device table.
![image](https://user-images.githubusercontent.com/1522389/52614332-46b07700-2ee1-11e9-942f-388e69b9040f.png)

Where-as it is fine in the device role overview.
![image](https://user-images.githubusercontent.com/1522389/52614335-4c0dc180-2ee1-11e9-8f18-6b1d7c907659.png)

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by stuntguy3000** [comment]
@jeremystretch Corrected
