### ISSUE TITLE
Enhance Unified Summaries

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#288]
I think unified summary pages like that site page are great!  

I would suggest that any of these stats would link to a filtered view of these stats  in the corresponding page.

I suggest we could introduce this across other unified pages such as:

**1.) Manufacturer:**
- total number of platforms
- total devices breakdown by device type
- total devices breakdown by platform (recommended: a manufacturer foreign key to be added to platform)
- total devices breakdown by device roles (I think data validation here may be over kill)

_*Note: I recommend the new foreign key to allow for data validation fields when selecting a platform for a device._

**2.) Rack Groups:**
- total devices
- total free RUs
- total used RUs
- total circuits (optional, may be over kill)

**3.) Device Types:**
- total devices

**4.) Prefixes:**
- % of IP space used or available?
- VLAN (if associated)

**4.) VRFs:**
- Number of prefixes

**5.) RIRs:**
- Number Prefixes
- % of IPs used/available?

**5.) Providers:**
- Number of circuits

Thoughts? Other suggestions?

**Comment by jeremystretch** [comment]
This feature request has languished for quite a while. Some of these have probably been addressed since it was open; others may or may not be addressed. I'm going to close this out but encourage people to open new requests for any specific details they'd like to see added (please limit the scope of a request to a single model).
