### ISSUE TITLE
Add Building PortMaps to Cable Trace

### ISSUE THREAD

**Issue by WatsonNet** [digitalocean/netbox#2960]
Hey Guys,
It would be really cool to be able to upload a building map of some sort, with the ability to either drag and drop port locations, or add en-masse to the map/picture and have these locations show up in the Cable Trace section.

We have several buildings with several racks and most have very different port numbering schematics, it would be cool yo have this visualised within the system easily when tracing a cable/device.

Cheers!

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by WatsonNet** [comment]
@jeremystretch Apologies, hopefully the edit above suffices?

Let me know if not!

Cheers!

**Comment by DanSheps** [comment]
@watsonnet endpoints can be modelled with the existing device type/devices.

**Comment by jeremystretch** [comment]
> Allow upload of building maps/floorplans of some sort
