### ISSUE TITLE
django-taggit-serializer's setup.py shows that it only works with python 2.6, 2.7 and 3.3

### ISSUE THREAD

**Issue by williamh** [digitalocean/netbox#3008]
Your requirements.txt lists django-taggit-serializer. If you look in the classifiers in this package's setup.py, it shows that it only works with python 2.6, 2.7 and 3.3. In the python 2 branch, my distro only supports python 2.7 (that will be removed by the end of the year I think) and we do not have python 3.3 at all.
Which versions of python do you test with? it looks like django-taggit-serializer may not be being maintained?

https://pypi.org/project/django-taggit-serializer/

Thanks for the information.

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
