### ISSUE TITLE
Port types for AV equipment

### ISSUE THREAD

**Issue by kdadev** [digitalocean/netbox#3020]
We have used NetBox on TV infrastructure management. To describe links between audio and video devices we have to add few port types.
**Video:** BNC-SDI, HD-BNC, BNC-CVBS, S-VIDEO and some vendor-specific
**Audio:** TRS, XLR, mini-TRS and some vendor specific.

I'm not sure that these additions should be pushed into main code, but for feature releases of NetBox it could be good for us to know, which constant values in **dcim/constants.py** should be best to use to escape possible incompatibility in the future.

Say, we get to use new constant `PORT_TYPE_VIDEO_HDBNC`. Which value is best to use for this constant to avoid intersection with new port types added in future releases? Is there any range of values for custom usage only?

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by DanSheps** [comment]
In addition to what Jeremy mentioned, this has been proposed in:

#2865
#1272

**Comment by kdadev** [comment]
You're right. Thanks.
