### ISSUE TITLE
Enable cookie-based sessions

### ISSUE THREAD

**Issue by kartiksubbarao** [digitalocean/netbox#3049]
I'd like to enable cookie-based sessions ([setting SESSION_ENGINE to "django.contrib.sessions.backends.signed_cookies")](https://docs.djangoproject.com/en/2.2/topics/http/sessions/#cookie-session-backend). My use case is a high-availability configuration where a VIP (netbox.example.com) is managed by keepalived on a master and hot standby replica. Users point to netbox.example.com in their browser. With cookie-based sessions, if the master crashed and keepalived flipped the VIP over to the replica, user sessions could transparently continue for read operations. (Also see this thread on the mailing list: [https://groups.google.com/d/msg/netbox-discuss/1tYF9d-wRl8/pfs1iAYOBAAJ](https://groups.google.com/d/msg/netbox-discuss/1tYF9d-wRl8/pfs1iAYOBAAJ))

Jeremy hinted at the possibility of exposing SESSION_ENGINE in the #2426 discussion. If this is practical to implement, I think it could be helpful for many users who want to deploy netbox in various ways.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
