### ISSUE TITLE
Expand Secrets to Include Racks and Rack Cages

### ISSUE THREAD

**Issue by jennec** [digitalocean/netbox#305]
In shared data centers there may be cages containing your Racks.  Each of those cages made have an access code, and each of the racks may also have access codes.  It would be handy to be able to store the access codes for cages and rack with those objects in NetBox.

**Comment by jeremystretch** [comment]
This was a consideration early on in NetBox development, but I figured the overhead and complexity introduced by employing a `GenericForeignKey` to map Secrets to multiple models isn't worth the limited gain. Realistically, most people probably don't need to encrypt lock combinations; most will be fine with storing them as plaintext in the comments of an object.

**Comment by rekkoner** [comment]
What about site-wide secrets, too. For things like product keycodes (VMware, windows, etc)?

**Comment by jeremystretch** [comment]
If it's not tied directly to a NetBox resource, it probably shouldn't be in NetBox. There are myriad general purpose password management tools out there.

**Comment by jallakim** [comment]
This makes sense for more than racks and rack cages. One example would be BGP key/password; it would probably make more sense to apply that secret to a Circuit (or Provider), than the actual device (e.g. when replacing the device, you'd need to add the secret again, but the circuit/provided would be the same).

**Comment by jeremystretch** [comment]
Tracking secrets for individual routing protocol adjacencies probably falls too far on the configuration management side, which NetBox does not attempt to breach. Operators are better off storing that data wherever they keep every other parameter of an adjacency (peer IP, route filters, timers, etc.).

I'm going to close this out because extending secrets beyond the Device model would introduce substantial complexity and overhead while yielding little additional value.
