### ISSUE TITLE
Add a new IP address

### ISSUE THREAD

**Issue by 9sm** [digitalocean/netbox#3057]
Cuando se agrega una IP desde
/ipam/prefixes/1/ip-addresses/

![imagen](https://user-images.githubusercontent.com/25819945/55881785-b6598000-5b79-11e9-8f01-b6c39ccfde90.png)

Add a new IP address
 y le das en "Create and add Another" no cambia la ip queda en la misma direccion. Deberia cambiar a la siguiente direccion.
Deja la misma ip y vacia y las duplica si no te das cuenta
saludos

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

Please also note that issues must be in English.
