### ISSUE TITLE
Expand search to description and comment fields (Ports, Interfaces...)

### ISSUE THREAD

**Issue by chrisdcn** [digitalocean/netbox#3076]
It would be great if expand global search to all description and comment fields. For example to "Front Ports" or "Interfaces"

### Environment
* NetBox version:  v2.5.8

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
