### ISSUE TITLE
IP Roles

### ISSUE THREAD

**Issue by alexey-kirillov** [digitalocean/netbox#3109]
First of all, thanks for Netbox.
I know there is a number of relevant issues, but let's try one more time :)

1. Router
It's not uncommon to have a single gateway on a subnet, which is a default gw for devices, why should we avoid documenting this? Let's call it a "router" role which means this IP can route ip packets to other networks. This would be an attribute of this IP (ability to route), not devices, which use this IP as a gateway.
In case you have multiple routers, it's up to you to mark them all.

2. Custom Role
There are cases when you want to highlight another role, such as DNS,DHCP. Someone will require another set of roles. Why don't you implement configurable list of roles? This is done for prefixes,vlans,racks,devices, but not for IPs.

3. Ok, we can use tags, but:
  a) some are not relevant for IPs (list of tags can be reduced by using IP roles instead)
  b) tags are not shown in IP list, which makes them hardly usable

4. And there's no comment field for all IPAM items :(

Thank you.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by alexey-kirillov** [comment]
fixed, please re-open
