### ISSUE TITLE
circuits.circuittermination is not listed in choices API for cable:termination_a/b_type

### ISSUE THREAD

**Issue by shanemadden** [digitalocean/netbox#3132]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.10 / 2.6 dev

### Steps to Reproduce
1. Create a cable with one end connected to the A or Z termination of a circuit
2. View that cable in the API, confirming that `termination_a_type` or `termination_b_type` is returned as `circuits.circuittermination`
3. View the `/dcim/_choices/` endpoint, confirm that `cable:termination_a_type` does not have `circuits.circuittermination` listed.

### Expected Behavior
Return a circuit termination 'choice' table in the _choices API for `cable:termination_a_type`/`cable:termination_b_type`:

    {
      "label": "circuit termination",
      "value": "circuits.circuittermination"
    },

### Observed Behavior
Only `dcim.*` object types are shown as choices for `cable:termination_a_type`/`cable:termination_b_type`

**Comment by jeremystretch** [comment]
I was trying to figure out why this wasn't causing issues when connecting a cable to a circuit termination. It's because the cable creation forms currently (in v2.5) only allow connecting a cable _from_ a circuit termination _to_ some device component; the "B" side is never a circuit termination. Hence why this was missed.
