### ISSUE TITLE
Allow "floating" ip address object types to be assigned to multiple interfaces

### ISSUE THREAD

**Issue by ossark** [digitalocean/netbox#3162]
### Proposed Functionality
Allow floating address types (HSRP, VRRP, CARP, Anycast etc) to be assignable to several interfaces on different devices.

### Use Case
Due to the nature of the above mentioned IP addresses, they are not unique even within a context that mandates uniqueness, it would mimic reality if these address types could be assignable to multiple interfaces.

With the current setting of "prevent duplicates" for IP addresses the above address types are rendered mostly useless. The only way currently of distinguishing the "ownership" of a floating address is either through the description field (very bad) or tags (bad). 

With the proposed functionality implemented it would be possible to utilize the floating ip address types properly while not having to create multiple ip address objects that are in fact separate objects in database but the same object in practice thereby breaking the database to reality representation.

**Comment by jeremystretch** [comment]
NetBox modeling virtual/floating IPs and IPs managed by NHRPs (VRRP, etc.) as individual IPs because it may be necessary to track unique attributes of each. For example, VRRP IPs typically each get a different priority value. (This isn't supported currently but see #2456.)

> With the current setting of "prevent duplicates" for IP addresses the above address types are rendered mostly useless.

NetBox permits the creation of IP addresses with these roles even if unique address enforcement is enabled. If you can identify a scenario where this does not work, please open a bug and detail the steps someone else can take to reproduce the issue.
