### ISSUE TITLE
VLANs Default Sort Change

### ISSUE THREAD

**Issue by rannday** [digitalocean/netbox#3169]
When using VLAN groups, when you go to VLANs, all groups are shown at the top. This is kind of annoying, because it puts all the VLANs out of order. Yes, you can change the sort, but why is this the default? 

Is there an option to change the default sort method? Or could you give us one?

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
