### ISSUE TITLE
Port Type EC2000

### ISSUE THREAD

**Issue by MrXermon** [digitalocean/netbox#3224]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.10

### Proposed Functionality
The Port-Type EC2000 should be added.

### Use Case
Document EC2000 patchpanels.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by MrXermon** [comment]
I've updated the request with more information about the feature request.
