### ISSUE TITLE
IPAM enhancement (network calc)

### ISSUE THREAD

**Issue by alexey-kirillov** [digitalocean/netbox#3236]
### Environment

* NetBox version:  2.5.13

### Proposed Functionality
Add detailed prefix info:
- dotted decimal notation for network mask
- inverse mask
- min/max ip
- size

### Use Case
Obviously, it would be helpful, e.g. copy an inverse mask to acl config.

### Database Changes
none

### External Dependencies
none

**Comment by jeremystretch** [comment]
These are essentially all just different ways of displaying the same information; it would be redundant to include them all on the UI.

> e.g. copy an inverse mask to acl config.

If you're doing this often enough that calculating the wildcard mask by hand is a burden, you should be looking to automate your workflow: That is, pulling the prefix via the API and scripting out the config from the data retrieved, to remove the manual process entirely.

**Comment by alexey-kirillov** [comment]
Absolutely correct for large infrastructure. API is one of the key features one should use.
But netbox is also a great tool for documenting small to medium-sized networks (surprisingly, you can find some world-readable instances in google inurl:"ipam/ip-addresses/"). And I'm sure most of them are maintained manually. In fact I'm missing this feature after migrating from racktables.
Anyway implementation shouldn't require much effort.

**Comment by baldoarturo** [comment]
I second this. I could do it too, I think everything can be handled inside the template.

**Comment by jeremystretch** [comment]
I think what bothers me most about this is that none of the listed points concern a specific prefix: They're all merely alternative formats of displaying a mask, and at that are mostly relevant only to IPv4.

> dotted decimal notation for network mask

An antiquated way of displaying the prefix length (e.g. `255.255.255.0` instead of `/24`), which most people have memorized anyway.

> inverse mask

Redundant to the above.

> min/max ip

This one is at least pertinent to a specific prefix, but the information is already available under the child IPs list.

> size

For any scenario where you're concerned with the actual number of IPs within a prefix, you've probably memorized this already anyway. Typically for IPv4 (and _always_ with IPv6) we talk about prefixes in terms of prefix length (e.g. /24) rather than absolute host count.

I'm going to close this out as I believe it would only introduce cruft to the prefix view, and the data in question is easily referenced on a [cheat sheet](https://packetlife.net/media/library/15/IPv4_Subnetting.pdf).
