### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by Chrisafis** [digitalocean/netbox#3238]
We would like to see a feature that we can use it to manage and keep track of our inventory that we have in our rack in the Data center.

It will important the feature to accept the following parameters and if it is possible to sent notification for the quantities of the inventory
   
Type, Model, Quantity, Description

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
