### ISSUE TITLE
Add subnet or broadcast in prefix

### ISSUE THREAD

**Issue by vourd** [digitalocean/netbox#3247]
### Environment
* Python version:  3.6.8
* NetBox version:  2.5.13

### Steps to Reproduce
1. Add prefix 
2. Enter prefix
3. Switch to tab 'IP Addresses'
4. Click on XXX IPs available for XXX.XXX.XXX.0/XX or XXX.XXX.XXX.255/XX ip addresses (even showing these as available)

### Expected Behavior
Not showing .0 or .255 ip addresses, since they are a subnet or broadcast address

### Observed Behavior
Can add .0 or .255 as useable address

![Clipboard02](https://user-images.githubusercontent.com/48771302/59025521-a4801a80-8854-11e9-8e48-43ee16ace4f0.jpg)
![Clipboard01](https://user-images.githubusercontent.com/48771302/59025522-a4801a80-8854-11e9-8cf3-484c70857e8a.jpg)
![Clipboard04](https://user-images.githubusercontent.com/48771302/59025524-a518b100-8854-11e9-89d0-317001d73e04.jpg)
![Clipboard03](https://user-images.githubusercontent.com/48771302/59025525-a518b100-8854-11e9-8b28-acb785a23917.jpg)

**Comment by ITJamie** [comment]
+1. seeing this on netbox 2.5.12 . broadcast ip is available to be assigned

**Comment by DanSheps** [comment]
This is most likely behaviour that has not been changed since initial release.

Couple of reasons for this:

1. Prefixes can be designated a "pool", in which case it would be perfectly valid to have a network and broadcast address
2. There may be specific reasons that you want to document the Network or Broadcast address, or perhaps you forgot to mark it as a pool
3. This has to be done manually, as in you have to consciously choose to input the network or broadcast address.  Both the UI and the API correctly return only the usable addresses available

I personally think the work required to implement the appropriate checks for this is better spent elsewhere.

**Comment by vourd** [comment]
Thanks for your feedback. I personally think broadcast addresses should never be used and subnet address is defined by prefix, but I understand it'd be a lot of work to do.

You now know about this issue, whether or not you'd like to fix this in future belongs to you/netbox team!
