### ISSUE TITLE
More information in user feedback messages

### ISSUE THREAD

**Issue by mike548141** [digitalocean/netbox#3250]
Enhancement request
When you push a user feedback message such as "Added 1 interfaces to Switch01." it would be helpful if it showed the name of the interface added e.g. "Added interface 16 to Switch01."

Great product thanks,

MC

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
