### ISSUE TITLE
Correct interface sort by type

### ISSUE THREAD

**Issue by mlimalotic** [digitalocean/netbox#3266]
Thank you for this great management tool. Is it possible sort by type of interface? Example, a switch with 24 FastEthernet and 2 GigabitEthernet, sort first Fa and second Gi?
Other example, sort by type Fast, Giga, Ten, Fourten, etc?

Below an image, Gi0/1 and Gi0/2 are last interfaces of switch

![image](https://user-images.githubusercontent.com/18513223/59726205-18cc9d80-9207-11e9-96a4-395c0979d981.png)

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
