### ISSUE TITLE
Assign VLANs to Regions and not only sites

### ISSUE THREAD

**Issue by Alex-Souslik** [digitalocean/netbox#3267]
We often have the same VLANs in several sites in our region and it's annoying being  to have recreate them in every site.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
