### ISSUE TITLE
Issue 3176 enhancement

### ISSUE THREAD

**Issue by aamsaleg** [digitalocean/netbox#3273]
Hi

Issue 3176 fixed in 2.6 release gives the trace button on the console server side but the same is missing on the device side.

Netbox version : 2.6
Screenshot on the console server ports:
![image](https://user-images.githubusercontent.com/25366020/59907292-0c189700-940b-11e9-8f06-3a8f83f954c9.png)

screenshot on the remote side:
![image](https://user-images.githubusercontent.com/25366020/59907361-32d6cd80-940b-11e9-81aa-39d3c18435a1.png)

If a next patch can add the trace button for devices (switch, servers, ...), we will have this feature on both ends.

Step to reproduce:
like issue 3176. 
link a switch console port to a patch panel (PP) front port
associated PP rear port is connected to another PP rear port in another rack
link associated front port to a console server port.
The trace button is only on the console server device, not on the switch device console port.

Best Regards
Alexandre.

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).
