### ISSUE TITLE
Exception when adding a power outlet to a device type

### ISSUE THREAD

**Issue by benohara** [digitalocean/netbox#3275]
### Environment
* Python version:  3.6.8
* NetBox version: 2.6.0

### Steps to Reproduce
1. On device type, click 'add components' and select 'power outlets'
2. Add a name (either singular or regex)  and click 'create'

### Expected Behavior
The device type should be updated with the requested ports

### Observed Behavior
The following exception is thrown

```
<class 'AttributeError'>

'PowerOutletTemplateForm' object has no attribute 'parent'
```

No ports are created on the 'device type'

This works on 'devices'

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by benohara** [comment]
Can you reopen
