### ISSUE TITLE
Update Instances to Count in Device-Type Template

### ISSUE THREAD

**Issue by hSaria** [digitalocean/netbox#3276]
### Environment
* Python version: 3.6.8
* NetBox version: 2.6.0

The Jinja template should be updated to reflect the recent change of `Instance_count` to `device_count` on the Device-Type. It currently still shows `Instances`.

### Steps to Reproduce
1. Browse to `netbox.example.com/dcim/device-types/` or `netbox.example.com/dcim/device-types/`. They both say `Instances` when referring to `device_count`.

### Expected Behavior
It'll show `Count`, `Device Count`, or `Devices`, preferably the last one (it'll match the Platforms page).

### Observed Behavior
It shows `Instances`.

**Comment by hSaria** [comment]
If I'm not mistaken, it needs to be updated in the following:
```./netbox/dcim/tables.py
./netbox/templates/dcim/devicetype.html
```

**Comment by DanSheps** [comment]
Personally, it doesn't bother me one way or the other.  The instance_count property was renamed to device_count for consistency within the API (in my opinion).




However, I have a different preference:

I personally would actually prefer instance, instead of count.  I look at it like this, such that a device is a sub of device_type, and each device would be an instance of device_type.  Contrast that to things like sites,  racks where they are containers for devices and don't directly correspond to devices in a

**Comment by hSaria** [comment]
Good point. I don’t mind either way. I just thought I’d mention it in case it was missed. If it wasn’t, feel free to close the issue.

**Comment by jeremystretch** [comment]
Yeah I'm fine leaving this as-is.
