### ISSUE TITLE
Connection showing as "not connected"

### ISSUE THREAD

**Issue by darkdane** [digitalocean/netbox#3303]
We are running Netbox 2.6.1.

We have a switch with two connections running through our DWDM muxes. Both connections have a working cable trace to the correct endpoint. 

But the switch is only showing one os connected to the endpoing. Is there a max number of hops in the cable trace to show the destination port inside the initial device? 

![image](https://user-images.githubusercontent.com/26304681/60335043-2fa88800-999d-11e9-9f93-2a33c068db01.png)

The upper connection has 5 cable trace hops (this is the working one) and the other connection has 10 cable trace hops, which is not showing the destination port. But Cable trace is fully connected to the destination port.

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by fablabo** [comment]
This is related to #3193 and #3288
