### ISSUE TITLE
Upgrade path recommendation

### ISSUE THREAD

**Issue by Fyzzle** [digitalocean/netbox#3306]
Heya, I'm a little behind and getting ready to upgrade from 2.4.4 to the latest master.  Is there a recommended upgrade path to take to get there? 

Thanks.

**Comment by DanSheps** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

This question would be better suited for the mailing list: https://groups.google.com/forum/#!forum/netbox-discuss
