### ISSUE TITLE
Rack Utilization Percentage for "Racked" Devices only

### ISSUE THREAD

**Issue by jbro209070** [digitalocean/netbox#369]
Sorry for making another post about this Jeremy, but you closed out the last one before I could finish posting my question. 

Say I were to take down a cisco 1921 router (1U) and put it on a shelf. Unless I were to change it to 0U in device types, it would still say that im utilizing rack space even when unracked. When I want to put it back on the rack, I would have to go into device types and change it back to 1U again. Is there a way to set utilization to only pull percentage off devices that are "racked" and ignore "unracked" device U height?

**Comment by jeremystretch** [comment]
This is intentional. Often, we know that certain devices exist within a rack, but we might not know the specific positions in which they're mounted (because we don't have immediate physical access to the rack to check). NetBox still allows us to assign a device to a rack and consider it as consuming space for inventory purposes.

If you've physically removed a device from a rack, it should be deleted from NetBox as well, as it no longer resides in that rack. As to whether NetBox can/should be used to track devices not installed in a rack, see #198.
