### ISSUE TITLE
Vlan name length limitation of 30 characters

### ISSUE THREAD

**Issue by Zanthras** [digitalocean/netbox#374]
Not a huge deal, but why the limit of 30 not 32 characters on the VLAN model? The upper limit for IOS has historically been 32.

**Comment by jeremystretch** [comment]
We just happen to use a 30-character limit for most (all?) object names. AFAIK there's no official limit on the VLAN name length, since the name is never carried on the wire. (The exception to this is Cisco's proprietary VTP, which seems to enforce, or at least suggest, a [20-character maximum](https://supportforums.cisco.com/discussion/11610686/vlan-names-exceeded-20-characters).)

I don't see any reason not to increase the VLAN name field to 32 characters.

**Comment by Zanthras** [comment]
NX-os forces 32 character vlan limits until a later version enabled a feature to make it longer, ios pre 15 seems to silently truncate on 32 chars. But in any case you want me to create a pull request to raise it? (I have a number of vlans names at 32 chars which i would like to import without modification)

**Comment by jeremystretch** [comment]
Well, is 32 characters long enough?

**Comment by Zanthras** [comment]
Im sure there are "interesting" deployments that have vlan names at extreme levels, But a smaller sane limit of say 128 that fits most? cases probably isnt bad.

**Comment by jeremystretch** [comment]
Based on [some feedback](https://www.reddit.com/r/networking/comments/4ujp9u/long_vlan_names/) I upped the name length to 64 characters in d241cce. Should be sufficient.

**Comment by Zanthras** [comment]
Sounds good to me!
