### ISSUE TITLE
route-target support

### ISSUE THREAD

**Issue by jtdub** [digitalocean/netbox#377]
Apologies if this has already been requested. I browsed through the open issues, but nothing stuck out.

It would be helpful to be able to assign VRF's to a sight. This means that we would need to be able to have duplicate VRF names, but only if the site doesn't currently have a VRF assigned to it by that name. 

Example:

Valid duplicate VRF:
```
VRF: Internet, Site: DFW
VRF: Internet, Site: ORD
```

Invalid duplicate VRF:
```
VRF: Internet, Site: DFW
VRF: Internet, Site: DFW
```

Then have the ability to assign the VRF with a default import/export route-target and the ability to import/export route-targets from already created VRF's. Thoughts?

**Comment by jeremystretch** [comment]
It doesn't make sense to assign a VRF to a site, since one VRF may span multiple sites. A VRF represents a routing table; it doesn't necessarily have any correlation to a physical site.

I do plan to implement RT-based import/export among VRFs at some point, but that's not related to the assignment of a VRF to a site.
