### ISSUE TITLE
Report functions

### ISSUE THREAD

**Issue by nqvan** [digitalocean/netbox#448]
Hi,

In current version, we don't have report function. Example:

- Rack using in site
- Free unit
-  Total unit using
...

**Comment by jeremystretch** [comment]
Could you please add more detail to this issue? This isn't sufficient to mark as a feature request.

**Comment by nqvan** [comment]
Hi jeremystretch,

I think report function helpful in Netbox. Example, my manager want to know: rack using statistics in site or rack group ( total u used in rack 24u, total free u in site/rack group), total device in site/rack group, total ip used...

**Comment by jeremystretch** [comment]
You can create your own reports for most objects using [export templates](http://netbox.readthedocs.io/en/latest/data-model/extras/#export-templates). NetBox doesn't include any default reports because everyone is bound to want different data in different formats. Export templates allow each user to extract precisely the information they want.
