### ISSUE TITLE
Disable rack face / position when creating child devices

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#461]
This is a follow-up of #327. The former issue requested to disable rack face and position fields for child devices, which has been implemented (c643e3a), when assigning child devices.
It has not been done if new devices with a child hardware type are going to be created. As I got no response on the other ticket and on IRC, I'm opening this new issue.

Would be great if you could implement this for the page "Devices/Add a device" (/dcim/devices/add/), too. :smile:

**Comment by jeremystretch** [comment]
Disabling these fields would require rewriting the entire live selection logic. This is probably best deferred until we revamp the UI to be API-driven in NetBox v3. However, I have improved form validation so that errors are now correctly displayed when attempting to mount a child device to a rack face/position.
