### ISSUE TITLE
Remove unique naming requirement for racks

### ISSUE THREAD

**Issue by ajleach** [digitalocean/netbox#525]
This may be more of a feature request, and I apologize if this has been covered before.

We have multiple Sites, and at each site we have similar naming schemes - Site A and Site B both have similar layouts, so the Rack in Row A, Position 1 will have a name of A1. However, we're not able to name the rack at this location the same in both sites, as Netbox requires a unique name for each rack even when in different sites. Is there any way to use unique IDs for each rack behind the scenes so that we can name the racks whatever we'd like, or is this restriction intentional?

We have noticed the same thing for Devices. For example, we have two patch panels named the same thing, however they are located in two different racks.

**Comment by chagara** [comment]
We have run into the same problem. For the moment, our work around has been adding the application in front of the hostname. EX. nginx rofl_nginx.dude.com

**Comment by ajleach** [comment]
@marvnrawley You're correct, I misunderstood what my network engineer was trying to do. It's actually within different rack groups in the same site that we're trying to have racks of the same name. Basically our 'sites' represent buildings, and 'rack groups' represent different rooms within that building (we basically have modular data centers). Were groups not intended to be used like this? Or is there a better way to accomplish what we're trying to do?

**Comment by marvnrawley** [comment]
For racks, there is no reason you couldn't have more than one site group. For example, I have also aligned rack groups with the comms room / data hall, but you could be more granular and name your site group for the cage/area within the data hall. So instead of just "Comms room 2" you could name your group "Comms room 2 Cage 1".

Equally, try assigning the duplicate CIs to two separate tenants, it might allow you to overlap names then?

Granted these are not suggestions for fixes. I personally think that unique rack names and unique device names is the way to go, and the data we are putting in is already compliant with that.

Perhaps you could make a case here for nested rack groups however so you can partition it down further.

For example, you might want to have your site as a building, your building might have multiple floors, and each floor could have more than one comms room, or indeed your equipment might be in "Provider DC 2", "Hall 3", "Cage D08" and "Cage D11" - right now this is flattened to just site and group but it might be useful to support nesting or even just one extra layer of sub group.

**Comment by jeremystretch** [comment]
This boils down to a trade-off between flexibility and convenience. If we allow multiple racks with the same name within a site, we can no longer refer to an individual rack by only its site and name; we would also need to specify its rack group, effectively requiring every rack to belong a rack group. This may or may not be acceptable.

**Comment by jeremystretch** [comment]
Going to roll this into #238
