### ISSUE TITLE
Attach Circuit to a prefix or IP Addresses

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#641]
Hi,

Would be possible in the furture to attach a Circuit to a prefix or ip addresses ?

Thanks in advance.

Best Regards,

Thomas V.

**Comment by jeremystretch** [comment]
IMO associating prefixes directly to circuits is too ambiguous as it doesn't convey information about usable IPs. It might also introduce problems when we extend the circuit model to attach two points instead of having a single anchor as it does currently.

For now, I've implemented #661 to include IP addresses from the interface to which a circuit is attached. This should be a sufficient method of tying a prefix to a circuit.
