### ISSUE TITLE
The first and last IP within a prefix are assumed to be unusable

### ISSUE THREAD

**Issue by NetTinkerer** [digitalocean/netbox#658]
when a /27 prefix is created only 30 free IPs are mentionned. Although this is valid for Ethernet segments it is confusing when the prefix is used as a pool for nat addresses or aggregating loopbacks. It might be usefull to add a flag to a prefix if it is an ethernet segement or just a container for something else

**Comment by jeremystretch** [comment]
It's pretty easy to modify this behavior, but we need to figure out how to indicate whether the network/broadcast IPs should be counted. It might make sense to add a new prefix type called "pool" and count otherwise unusable IPs for prefixes of this type. It might also make sense to count them for container prefixes.

**Comment by footplus** [comment]
FWIW, RackTables work around this by using "reserved" addresses, that a checkbox permits to allocate easily while creating the prefix. That way, every prefix is useable as a pool or not.
