### ISSUE TITLE
Confused about IPAM part

### ISSUE THREAD

**Issue by soamz** [digitalocean/netbox#697]
Okay, we are a ISP and we have 200 private devices all in 10.10.12.xx IP addresses. 

We simply need to add each device here and specify its IP as 10.10.12.x and make sure, the device and the IP shows. 

But Im confused about the workflow al together for the IP. 

When i goto IP, it asks me to enter /xx , which I dont need. 
It confuses the team if I enter 10.10.12.xx/32

I simply need it to manage show as DEVICE ABC - 10.10.12.125 

Simple.

How to achieve or what am I missing ?

**Comment by jeremystretch** [comment]
The mask is part of the IP address. You cannot configure an IP address on an interface without also specifying a mask.

**Comment by soamz** [comment]
Okay whats the workflow then ?

How should I manage the IP addresses stitched to the devices ?

**Comment by LBegnaud** [comment]
if you put the ip as 10.10.12.125/24 and set the flag to make it the primary IP, only the IP will show up in the devices list.

the subnet is an integral part of the ip and must be included. sounds like you just need to define one prefix: 10.10.12.0/24, then every ip you assign will be part of that prefix

**Comment by soamz** [comment]
Okay lets say I want to search which device has 10.10.12.212 IP, how will I find it out with one search click ?

**Comment by LBegnaud** [comment]
not sure if it can be done faster, but this works just fine for us:

![image](https://cloud.githubusercontent.com/assets/15981748/20435375/7cf7c348-ad71-11e6-9793-eede7d1e016a.png)

click search, it pulls up the ip, which is linked to the device

**Comment by soamz** [comment]
Can you show me your devices page and IP page ?

Im confused completely. 

You said, we cannot show as DEVICE A - 10.10.12.24 etc

**Comment by LBegnaud** [comment]
This is the result of searching specifically for ip 10.250.100.1

![image](https://cloud.githubusercontent.com/assets/15981748/20493842/09cd029a-afe0-11e6-878f-3334ebb756ca.png)

and this is what my device listing looks like when sorted for just that device (not trying to expose too much of our internal info

![image](https://cloud.githubusercontent.com/assets/15981748/20493906/43766c7a-afe0-11e6-93bc-0ff6281f6bad.png)

**Comment by therealjoshuad** [comment]
@lbegnaud I recognize that data center. I knew with a name like that, you had to be from the same area as me.

**Comment by soamz** [comment]
It shows /24 , means whole block for one device ?
How confusing ?

**Comment by LBegnaud** [comment]
@soamz its IP address is "10.250.100.1/24" the subnet mask is part of the address.

**Comment by soamz** [comment]
Can someone share some video or screenshots ?

Im still lost about how to see my specific devices with specific IP addresses and not with subnet mask.

**Comment by therealjoshuad** [comment]
@soamz hopefully this can help:
If you're using a subnetmask of **255.255.255.0**, that is represented by **/24** on the end of the IP Address.

Example: If I want to add **10.10.12.125** as part of the **10.10.12.xx** network, I'd enter it as **10.10.12.125/24**
![image](https://cloud.githubusercontent.com/assets/3893036/20980472/4adba92e-bc76-11e6-8b17-e7d4d9dee1a2.png)
![image](https://cloud.githubusercontent.com/assets/3893036/20980481/53b76d80-bc76-11e6-85aa-0a7a97652958.png)

If you're tracking all of the IPs in the **10.10.12.xxx** network, you'd then create a **_Prefix_** for it:
![image](https://cloud.githubusercontent.com/assets/3893036/20980563/a63eddd6-bc76-11e6-89d8-6136f03d9e4b.png)
The IP addresses you entered with the /24 notation will all show up under the prefix
![image](https://cloud.githubusercontent.com/assets/3893036/20980580/c0ba8c0a-bc76-11e6-948b-d698e302db66.png)
The Prefix is handy because you can look at all of the IP addresses within a network.

If you prefer to not group them by prefix at all, and have each IP address be an individual network, you would use a **/32** (_255.255.255.255_) notation.
![image](https://cloud.githubusercontent.com/assets/3893036/20980683/2111151a-bc77-11e6-8a57-5cbd1ddd0c1f.png)
![image](https://cloud.githubusercontent.com/assets/3893036/20980702/36f8e2f4-bc77-11e6-879a-995389cfe90d.png)


CIDR Notation Cheatsheet: https://oav.net/mirrors/cidr.html
CIDR notation Explained: https://www.digitalocean.com/community/tutorials/understanding-ip-addresses-subnets-and-cidr-notation-for-networking

**Comment by soamz** [comment]
Yes I was thinking to put all devices with /32 as /24 will confuse my teams. 

This seems a clear explanation. 
I will be checking tomorrow and see if I can organize the devices well.
