### ISSUE TITLE
Crash when device name is a number greater thant an integer.

### ISSUE THREAD

**Issue by Mmoi-Fr** [digitalocean/netbox#747]
Hi,

I got an error after I added the device named "N010025001001".

When I try to see the devices from the city where that device is, I get a "Django.utils" error saying that the name exceed the integer limits.

The only way to correct this was to delete the device in postgres itself...

Could you check it out?

Thx

**Comment by jeremystretch** [comment]
This was due to the way we implement natural ordering for device names. This ensures that, for example, a device named router30 shows up between router1 and router100. We do this by casting the trailing numeric portion as an integer and sorting on it separately.

In this case, NetBox was attempting to cast the number 10025001001 as an integer, which is too big to fit the type (the maximum value of a signed four-byte integer is 2147483647). I've adjusted the regex to match only up to nine digits, which ensures that the captured value can be converted to an integer. This approach can likely be improved, but be should be sufficient in the short term.
