### ISSUE TITLE
Multiple NAT Entries for one IP address (Port-Forwarding/PAT)

### ISSUE THREAD

**Issue by nonsbe** [digitalocean/netbox#788]
Dear Jeremy,

**Feature Request/Roadmap description:**
It would be nice to have the ability to enter mutliple NAT lines in the IP address entry. 
We currently have a pool of public IP addresses that are used for one-to-one NAT (which is already implemented) and another pool that is used for port-forwarding purposes.

**For example:**
Prefix: 1.1.1.0/28 - Public IP Pool for PAT/Port-Forwarding
IP Address: 1.1.1.1/28

Currently you can only assign one inside IP address to this entry. 
A roadmap feature could be that you can choose the type of NAT used. Once you select the correct type -> Port-Forwarding. The input fields could change to something as

- Outside Port: <TCP/UDP Port Number>
- Inside IP Address: <IP Address> cross VRF capable (since the Public IP space is in another VRF as the customer internal IP addresses
- Inside Port: <TCP/UDP Port Number>

An extra **+** sign to add a new port forwarding entry. In this manner it would easen the case to manage our public IPs and services being exposed to the internet.

Further comments or improvements are welcome.
Thank you for your time,
Kind Regards,
N. D.

**Comment by jeremystretch** [comment]
NetBox's role is in infrastructure management, e.g. IPAM and DCIM. We've recently introduced the ability to attach discrete L4 services to devices, but that's as far as we'll go. NetBox supports NAT mappings because it's crucial to the management of IP resources. Port address translation, however, crosses the boundary into policy management, which is out of scope for NetBox.

**Comment by jennec** [comment]
Its still possible to have more than one NAT rule pointing the same inside IP.  So there is still a case for this in Netbox.  

For example, we have multiple external IP addresses with NAT rules through to the same internal IP address. This is because multiple service types run on these devices which require dedicated external IP addressing.

Could you revisit this request please?

**Comment by Hossy** [comment]
I agree with @jennec.  I would also ask that this issue be reconsidered from a PAT perspective.  I don't think this is a policy issue.  If this tool is going to manage IP addresses, I need to be able to document how those IPs are being used.  The knowledge/documentation that they are used without the information answering "how?" is IMHO useless.

There needs to be a many-to-one and one-to-many (by port) relationship to establish proper documentation.

**Comment by martinpsiddall** [comment]
I agree with @Hossy .. in terms of IP management, we need to track which external IP & Service is mapped to which internal address, and potentially multiple addresses when you want to define a load-balanced PAT. The ability to store the information is essential to a solution design and IPAM management, could this feature request be reconsidered?
