### ISSUE TITLE
Redirect back to rack when editing/deleting a device

### ISSUE THREAD

**Issue by Gelob** [digitalocean/netbox#832]
If you view a rack and click on a device to edit it, you are returned to the main devices page instead of the rack you were editing. You may be editing the device to unrack it, move rack positions, or even delete it.

**Comment by jeremystretch** [comment]
What link are you clicking from the rack view? AFAICT there's no direct link to edit a device; you have to first go to the device, and then edit it. Although there is a direct link to _add_ a device from the rack view.

**Comment by Gelob** [comment]
I'm clicking the device and then editing it as you described. I see the logic in why it would direct back to devices but I wasn't sure if there was a way to detect where you edited the device from or not.

**Comment by jeremystretch** [comment]
After editing a device, you should be returned to the view showing that device. Or are you talking about bulk-editing a set of devices?

**Comment by Gelob** [comment]
Not talking about bulk editing. I must be thinking of a different scenario because you are right and I can't seem to re-create the issue I was having now.

**Comment by 0lzi** [comment]
When in URL `/dcim/racks/XXX/` you select a device to delete it takes you to `dcim/devices/XXX/` you select delete and takes you to `dcim/devices/XXX/delete/` after confirmation it takes you to `/dcim/devices/ `

I think a redirect from `dcim/devices/XXX/delete/` back to `/dcim/racks/XXX/` would be worth doing if you have to delete a lot of items from a rack, otherwise you have to either navigate back three times to get back to the rack or select Site > Rack to get back to the rack you were working on.
