### ISSUE TITLE
Customizable Device Type > Interface > Form Factor

### ISSUE THREAD

**Issue by topside844** [digitalocean/netbox#84]
The 'Form Factor' list is missing "10GE (Copper)" and/or "100M/1G/10G (Copper)" types used on 10GBASE-T devices like Cisco's Nexus 93120TX switch.

This can be resolved by either making the Form Factor list customizable, or adding the necessary 10GBASE-T form factor (which is *not* available in 10GE SFP+ form factor due to limited SFP+ power).

**Comment by jeremystretch** [comment]
Will add this and probably some others to the static list. Definitely want to avoid custom interface form factors since only a finite set exists in the real world.

**Comment by bellwood** [comment]
Could I request Cisco "10GE X2 SFP" ... Cisco's 3750E's (and others) use this

**Comment by candlerb** [comment]
Although this issue is long closed, I would like to a add a couple of points.

* The set of connectors which exist in the real world, whilst mathematically *"finite"*, is much larger than Netbox currently supports.  Currently open requests for additions include #1865, #1941, #2865, and there have been many others which were accepted and closed.

    A static list will never meet everyone's needs - but as it gets larger, it will leave users having to scroll through many which are irrelevant to their environment (example: many exotic stacking cables for vendors which you don't use)

* I disagree with the assertion in #94 that making the list customisable *"would introduce a significant performance hit.*".  This is premature optimisation.  At worst, you read the table once into RAM at startup, and whenever an edit is made to the list - performance is then identical to today.

    Device Roles are customisable, and performance doesn't suffer.

There is always "Other" plus interface description, but this does not work well in an environment where you have many interfaces of a very specific type (e.g. in my case, many RF 'F' connectors for satellite feeds)
