### ISSUE TITLE
Cluster (shared or mobile IP address)

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#875]
(Relates to #142 but I thought it worth raising as separate feature request for the non-VM use case)

There are cases where you have a single IP address that relates to multiple devices. Examples:

* A switch stack with a single management address
* A pair of routers with HSRP/VRRP gateway address
* A ganeti cluster with a floating management address
* A pair of Windows servers running windows clustering

In each case, there are one or more shared management or service addresses; at any instant in time they can be served by any device in the group. Logically, the whole group provides a service on that address.

At the moment, you need to either leave the address not associated to any device, or associate it with only one device.

In the current DCIM model, this could be better implemented as a "device group" where you are able to associate an address with the group (or a virtual interface on the group)

----- 

However, once VMs are brought into the picture (#142), the concept can be more general:

* A cluster is also somewhere that VMs can run
* A cluster can consist of physical devices and/or VMs (e.g. a Kubernetes cluster which is formed out of VMs)
* You can have a cluster without any DCIM inventory (e.g. a cluster called "Amazon us-west-1")

At this point, it's more than just a Device Group.

**Comment by jeremystretch** [comment]
I see at least two separate concepts in play here: shared control planes and virtual IPs. Shared control planes (e.g. switch stacks) was tackled initially in #99 but isn't being pursued currently due to the investment required in time and effort. I'd like to revisit it at some point in the future.

Virtual IP addresses (VIPs) are likely addressed sufficiently by #819, which would allow a user to designate an IP address as a VRRP address, for example. I'm not sure that explicitly assigning a VIP to a set of interfaces is particularly valuable, but we can re-evaluate that once #819 has been implemented.

Finally, in the interest of keeping the list of issues manageable, I'd like to set aside any discussion of VM clustering until VM support (#142) is added to NetBox. Does that sound like a reasonable approach?

**Comment by candlerb** [comment]
I think there is value in linking a VRRP address to a set of devices: it is useful for monitoring purposes (e.g. if this virtual address stops working, you know which devices to look at), and perhaps more importantly, for configuration changes you know where to go.  And similarly, a cluster management address typically floats between devices in the cluster.

But I'm happy to see how #142 goes and take it from there.
