### ISSUE TITLE
Interace Form factor should be configurable

### ISSUE THREAD

**Issue by blubber19447** [digitalocean/netbox#97]
Would be nice to add SAS here. So you can manage your storage connection.

**Comment by jeremystretch** [comment]
Interface form factors are statically defined in NetBox because a) there aren't that many of them, and b) defining form factors as separate objects in the database would introduce a significant performance hit.

We can always add standardized form factors to NetBox (see #84). That said, SAS isn't strictly a network interface and IMO wouldn't make sense in this context.

**Comment by jeremystretch** [comment]
Going to close this particular issue, but if there are any additional interface form factors you'd like to see added, please open a new feature request for them.
