### ISSUE TITLE
Display child device interfaces on parent device interface list

### ISSUE THREAD

**Issue by pstanczak-vidscale** [digitalocean/netbox#970]
Feature request:
Ability to display child device interfaces on parent device interface list.
This way all interfaces from all device bays are displayed in parent device interface list, without the need to drill into individual bay child devices to see all the interfaces and circuits connected to them.
Child interfaces could be marked with a tag representing bay they belong to.

**Comment by dhoutz** [comment]
I'd like to second this request. Being able to see all interfaces on one page even when using child device bays would be very beneficial.

**Comment by jeremystretch** [comment]
I've thought about this a bit, but I'm going to reject this because I feel it convolutes what a device bay is intended to represent. A device bay holds a child device, which is an entirely separate logical entity; the components of one child have no relation to the components of another child within the same device. This is in contrast to the new type of relationship that we want to model in #824, which will represent modules within a device which each contain their own components.

I understand that in some situations it would be convenient to display all child device interfaces on one page, but in others it can lead to confusion, particularly when you consider the workflow of creating, editing, and deleting interfaces.
