### ISSUE TITLE
Interface Connections not displaying

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#998]
When viewing the "Interface Connections" page, no connections are being displayed for interfaces that are connected to each other.

I have something like this
`DEVICEA -- INTERFACE -- CIRCUIT -- INTERFACE -- DEVICEB
`
Both devices show the interface is attached to a remote device over a circuit.

**Comment by jeremystretch** [comment]
This is expected behavior. Logically, interface connections are represented as

```
Interface <-- InterfaceConnection --> Interface
```

whereas circuit connections are represented as

```
Interface <-- CircuitTermination <-- Circuit --> CircuitTermination --> Interface
```

This alternate model is necessary because each circuit termination may or may not be attached to a particular interface.

While I understand your reasoning, the two are very different types of connections, so I don't think it makes sense to include both in the same list. This is probably better solved by enhancing the circuit import/export ability (see #815).

**Comment by InsaneSplash** [comment]
OK Thanks, I was wondering if I was going mad, there was a bug or I was doing something wrong :)

Maybe something one could look in to adding in the future for additional reporting/auditing.
